!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 29 Jul 2025 17:17
!
MODULE MAIN_MODULE_DIFF
  USE BUFLOWMODULE_DIFF
  USE MESHDEFORMATIONN_DIFF
!!!!!!!!!!      
!!!!!!!!!!	 
  IMPLICIT NONE

CONTAINS
! 模块内包含子程序，自动生成显式接口
  SUBROUTINE MAIN(data_4d137, cellprimitivesout)
    USE TYPESMODULE_DIFF
    IMPLICIT NONE
! 输入参数：仅原data_4D137的第一个维度（标量）
    REAL(kind=8), ALLOCATABLE, INTENT(OUT) :: cellprimitivesout(:, :)
    REAL(kind=8), INTENT(IN) :: data_4d137(1, 4)
!!!!!!!!!!!!!!!!!!!!!!!!
	real(kind=8), allocatable :: cellPrimitivesoutb(:,:) 
    real(kind=8) :: data_4D137b(1,4)  
!!!!!!!!!!!!!!!!!!!!!!!!
! 传递变形网格点的变量
    INTEGER(kind=8) :: ncells, meshinfo(4), iostat, nlines_points, &
&   file_unit_points, nfaces, nfaceperbdry, nboundaries, nlines_boundary&
&   , file_unit_boundary, nlines_owner, file_unit_owner, &
&   nlines_neighbour, file_unit_neighbour, nlines_faces, file_unit_faces&
&   , startline_faces, fcount, i, bracketl, bracketr, pt_count
    INTEGER(kind=8) :: bcount, startline_boundary, npoints
!        real(kind=8), allocatable :: point_update(:,:)  
    CHARACTER(len=256) :: meshpath, pointsfilepath, boundaryfilepath, &
&   ownerfilepath, neighbourfilepath, facesfilepath, line
	INTEGER(kind=8) :: n_adj, niter_adj
    REAL(kind=8) :: resnorm_adj, dJdp_partial(4), jb_seed
    REAL(kind=8), ALLOCATABLE :: b_adj(:), psi_adj(:), dJdp(:)
    TYPE(MESHDATA) :: tempmesh
    INTRINSIC TRIM
    INTRINSIC INDEX
    INTRINSIC SIZE
    INTRINSIC MAXVAL
    INTRINSIC ALLOCATED
!!!!!!!!!!!!
!        data_4D137b(1,1:4) = 0.0d0
!!!!!!!!!!!!
!!!!!!!!!!!!!!meshdeformation
    file_unit_points = GET_FREE_UNITT()
    meshpath = 'mesh/OFairfoilMesh'
    pointsfilepath = TRIM(meshpath)//'/points'
    OPEN(unit=file_unit_points, file=pointsfilepath, status='old', &
&  action='read', iostat=iostat) 
    nlines_points = 0
    DO 
      READ(file_unit_points, '(a)', iostat=iostat) 
      IF (iostat .NE. 0) THEN
        REWIND(file_unit_points) 
        ALLOCATE(lines_defor(nlines_points))
        boundaryfilepath = TRIM(meshpath)//'/boundary'
        file_unit_boundary = GET_FREE_UNIT()
        OPEN(unit=file_unit_boundary, file=boundaryfilepath, status=&
&      'old', action='read', iostat=iostat) 
        nlines_boundary = 0
        DO 
          READ(file_unit_boundary, '(a)', iostat=iostat) 
          IF (iostat .NE. 0) THEN
            REWIND(file_unit_boundary) 
            ALLOCATE(blines(nlines_boundary))
            DO i=1,nlines_boundary
              READ(file_unit_boundary, '(a)') blines(i)
            END DO
            CLOSE(file_unit_boundary) 
            CALL OFFILE_FINDNITEMSSS(blines, startline_boundary, bcount)
            ALLOCATE(boundarynumfacess(bcount))
            ALLOCATE(boundarystartfacess(bcount))
            ownerfilepath = TRIM(meshpath)//'/owner'
            file_unit_owner = GET_FREE_UNIT()
            OPEN(unit=file_unit_owner, file=ownerfilepath, status='old'&
&          , action='read', iostat=iostat) 
            IF (iostat .NE. 0) THEN
              PRINT*, 'Error: Can''t open owner file: ', TRIM(meshpath)
              RETURN
            ELSE
              nlines_owner = 0
              DO 
                READ(file_unit_owner, '(a)', iostat=iostat) 
                IF (iostat .NE. 0) THEN
                  REWIND(file_unit_owner) 
                  ALLOCATE(lines_owner(nlines_owner))
! 2. 打开文件（与owner逻辑完全一致）
                  neighbourfilepath = TRIM(meshpath)//'/neighbour'
                  file_unit_neighbour = GET_FREE_UNIT()
                  OPEN(unit=file_unit_neighbour, file=neighbourfilepath&
&                , status='old', action='read', iostat=iostat) 
                  IF (iostat .NE. 0) THEN
! 错误信息与owner格式统
                    PRINT*, 'Error: Can''t open neighbour file: ', TRIM(&
&                   meshpath)
                    RETURN
                  ELSE
                    nlines_neighbour = 0
                    DO 
! 逐行读取计数
                      READ(file_unit_neighbour, '(a)', iostat=iostat) 
                      IF (iostat .NE. 0) THEN
                        REWIND(file_unit_neighbour) 
! 重置文件指针
                        ALLOCATE(lines_neighbour(nlines_neighbour))
! 分配存储所有行的数组
                        facesfilepath = TRIM(meshpath)//'/faces'
                        file_unit_faces = GET_FREE_UNIT()
                        OPEN(unit=file_unit_faces, file=facesfilepath, &
&                      status='old', action='read', iostat=iostat) 
                        IF (iostat .NE. 0) THEN
                          PRINT*, 'Error: Can''t open faces file: ', &
&                         TRIM(meshpath)
!            allocate(faces%faces(0))
                          RETURN
                        ELSE
                          nlines_faces = 0
                          DO 
                            READ(file_unit_faces, '(a)', iostat=iostat) 
                            IF (iostat .NE. 0) THEN
                              REWIND(file_unit_faces) 
                              ALLOCATE(lines_faces(74151))
                              DO i=1,nlines_faces
                                READ(file_unit_faces, '(a)') lines_faces&
&                              (i)
                              END DO
                              CLOSE(file_unit_faces) 
                              CALL OFFILE_FINDNITEMSSS(lines_faces, &
&                                                startline_faces, fcount&
&                                               )
                              ALLOCATE(tmp_faces(fcount))
!       do i = 1, fCount
!      		allocate(tmp_faces(i)%points(4))
!       end do
                              PRINT*, 'ABC'
                              DO i=1,2
                                line = TRIM(lines_faces(startline_faces+&
&                                 i-1))
                                bracketl = INDEX(line, '(')
                                bracketr = INDEX(line, ')')
                                READ(line(1:bracketl-1), *) pt_count
                              END DO
                              ALLOCATE(pts_faces(pt_count), source=&
&                             0_int64)
!		allocate(wing_update(99, 2), source=0.0_real64)
!!!!!!!!!!!!!!
!!!!!!!!!!!!!!Buflow
                              ALLOCATE(owner_tempmesh(0))
                              ALLOCATE(neighbour_tempmesh(0))
                              ALLOCATE(facepoints_tempmesh(0, 0))
                              PRINT*, 'A'
                              ALLOCATE(points_tempmesh(37243, 3))
                              CALL READOPENFOAMMESHH(meshpath, tempmesh)
                              PRINT*, 'ABC'
                              npoints = SIZE(points_tempmesh, 1)
                              nfaces = SIZE(owner_tempmesh)
                              ncells = MAXVAL(owner_tempmesh)
!四种边界
                              nboundaries = SIZE(tempmesh%boundarynames)
!所有边界面的总数
                              nfaceperbdry = SIZE(tempmesh%&
&                               boundarynumfaces)
                              ALLOCATE(currentboundary(nfaceperbdry))
                              ALLOCATE(gradp(ncells, 3))
                              ALLOCATE(sj(ncells))
                              ALLOCATE(sjcount(ncells))
                              ALLOCATE(rj(ncells))
                              ALLOCATE(rjsjf(nfaces, 2), source=0.0_8)
                              ALLOCATE(eps2(nfaces), source=0.0_8)
                              ALLOCATE(eps4(nfaces), source=0.0_8)
                              ALLOCATE(p_matrix(ncells, 1))
                              ALLOCATE(facevals(nfaces, 5))
!		allocate(P_eps(nCells))
                              ALLOCATE(temp_grad(ncells, 1, 3))
!这个是正确写法，错误写法在程序运行完之后会报错。正确写法和错误写法结果一样
                              ALLOCATE(timefluxes(ncells))
                              ALLOCATE(surfaceareas(ncells))
                              ALLOCATE(timefluxess(ncells))
                              ALLOCATE(surfaceareass(ncells))
                              ALLOCATE(facerhot(nfaces, 2), source=0.0_8&
&                             )
                              ALLOCATE(cellrhot(ncells, 2), source=0.0_8&
&                             )
                              ALLOCATE(facevel(3))
                              ALLOCATE(positionn(3))
                              ALLOCATE(fdeltas(nfaces, 5), source=0.0_8)
                              ALLOCATE(fdgrads(ncells, 5, 3))
                              ALLOCATE(eps22(nfaces))
                              ALLOCATE(eps44(nfaces))
                              ALLOCATE(epss(nfaces, 2), source=0.0_8)
                              ALLOCATE(diffusionflux(5))
                              ALLOCATE(unitfa(3))
                              ALLOCATE(fd(5))
                              ALLOCATE(farownerfd(5))
                              ALLOCATE(farneighbourfd(5))
!        allocate(fluxResidualss(nCells, 5), source=0.0_8) 
                              ALLOCATE(dt_val(ncells), source=0.0_8)
!		allocate(first5_refs(5,3))	
                              ALLOCATE(encodeprimitives3dd(ncells, 5))
                              ALLOCATE(initialvalues(5))
! 分配结构体数组
                              ALLOCATE(cellprimitives_sln(ncells, 5), &
&                             source=0.0d0)
                              ALLOCATE(cellstate_sln(ncells, 5), source=&
&                             0.0d0)
                              ALLOCATE(cellfluxes_sln(ncells, 15), &
&                             source=0.0d0)
                              ALLOCATE(fluxresiduals_sln(ncells, 5), &
&                             source=0.0d0)
                              ALLOCATE(facefluxes_sln(nfaces, 15), &
&                             source=0.0d0)
                              ALLOCATE(faces_mesh(nfaces, 2))
                              ALLOCATE(favecs_mesh(nfaces, 3))
                              ALLOCATE(fcenters_mesh(nfaces, 3))
                              ALLOCATE(cells_mesh(ncells, 6))
                              ALLOCATE(cvols_mesh(ncells))
                              ALLOCATE(ccenters_mesh(ncells, 3))
                              ALLOCATE(cellsizes_mesh(ncells, 3))
                              ALLOCATE(boundaryfaces_mesh(nboundaries, &
&                             MAXVAL(tempmesh%boundarynumfaces)))
                              ALLOCATE(dt_solve(ncells))
                              ALLOCATE(sol(ncells, 5))
                              ALLOCATE(fcs(6, 3))
                              ALLOCATE(cell_favecs(6, 3))
                              ALLOCATE(cellpts(0, 3))
!        allocate(cellPtss(1,3)) 
                              ALLOCATE(facepts(SIZE(facepoints_tempmesh(&
&                             1, :)), 3))
                              ALLOCATE(cellfacecount(ncells))
                              ALLOCATE(uunitvec(3))
!        allocate(points_tempMesh(size(point_update,1), size(point_update,2))) !在readOFPointsFilef里面已经allocate
                              ALLOCATE(points_meshdefor(37254, 3), &
&                             source=0.0_8)
                              ALLOCATE(inoutput(99, 2))
                              ALLOCATE(wing(99, 2))
                              ALLOCATE(wing_coords(99, 2))
                              ALLOCATE(inoutput_coords(99, 2))
                              ALLOCATE(control_points(198, 2))
                              ALLOCATE(r_row(198))
                              ALLOCATE(phi_row(198))
                              ALLOCATE(mat_inv(198, 198), source=0.0_8)
                              ALLOCATE(distances(198))
                              ALLOCATE(phi(198, 198))
                              ALLOCATE(point_update(npoints, 3))
!!!!!!!!!!!!!!Buflow
!       !$AD intent(out) :: cellPrimitives(nCells, 5)  ! 强制 Tapenade 识别维度（nCells 已定义）[-0.75d0, 0.485d0, -0.
!588d0, -0.912d0]
! 构造变形参数（仅第一个维度为输入，其余为0）        
! 读取网格
!		meshPath = "mesh/OFairfoilMesh"	
!		mesh = OpenFOAMMesh(meshPath, point_update)
! 修改后的代码
!		meshInfo = unstructuredMeshInfo(mesh) 
!		nCells = meshInfo(1)  
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                              ALLOCATE(cellprimitivesout(18513, 5), &
&                             source=0.0_8)
                              ALLOCATE(fluxresiduals(ncells, 5), source=&
&                             0.0_8)
							          ! === adjoint (b) variables allocate ===
        ! 對應 gradP, P_matrix, temp_grad, faceVals
							allocate(gradPb(nCells, 3))
							allocate(p_matrixb(nCells, 1))
							allocate(temp_gradb(nCells, 1, 3))
							allocate(faceValsb(nFaces, 5))

							! 對應 sj, rj, rjsjF
							allocate(sjb(nCells))
							allocate(rjb(nCells))
							allocate(rjsjFb(nFaces, 2))

							! 對應 eps2, eps4
							allocate(eps2b(nFaces))
							allocate(eps4b(nFaces))

							! 對應 eps22, diffusionFlux, unitFA, fD, epss
							allocate(eps22b(nFaces))
							allocate(diffusionFluxb(5))
							allocate(unitFAb(3))
							allocate(fDb(5))
							allocate(epssb(nFaces, 2))

							! 對應 fDeltas, fDGrads
							allocate(fDeltasb(nFaces, 5))
							allocate(fDGradsb(nCells, 5, 3))
							! 對應 cellState_sln, cellFluxes_sln, cellPrimitives_sln,
							!       fluxResiduals_sln, faceFluxes_sln
							allocate(cellState_slnb(nCells, 5))
							allocate(cellFluxes_slnb(nCells, 15))
							allocate(cellPrimitives_slnb(nCells, 5))
							allocate(fluxResiduals_slnb(nCells, 5))
							allocate(faceFluxes_slnb(nFaces, 15))

							! 對應 cVols_mesh, cCenters_mesh, fAVecs_mesh, fCenters_mesh
							allocate(cVols_meshb(nCells))
							allocate(cCenters_meshb(nCells, 3))
							allocate(fAVecs_meshb(nFaces, 3))
							allocate(fCenters_meshb(nFaces, 3))

							! 對應 facePts, fCs, cell_fAVecs
							allocate(facePtsb(size(facePoints_tempMesh(1, :)), 3))
							allocate(fCsb(6, 3))
							allocate(cell_fAVecsb(6, 3))

							! 對應 UunitVec, points_tempMesh, point_update
							allocate(uunitVecb(3))
							allocate(points_tempMeshb(37243, 3))
							allocate(point_updateb(nPoints, 3))

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
							allocate(cellPrimitivesoutb(18513, 5), source=0.0_8)
							data_4D137b(1,1:4) = 0.0d0
							allocate(fluxResidualsb(nCells, 5), source=1.0_8)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                              PRINT*, 'ABC'
! 调用网格变形，获取变形后的网格点（point_update）
                              CALL AIRFOIL_DEFORMATION_HH(data_4d137)
                              PRINT*, 'ABC'
! 调用CFD计算，传入变形网格点，输出结果到cellPrimitives
                              CALL COMPUTE_CFD(cellprimitivesout)
                              ! 正向：填 fluxresiduals（供后续 ADJOINT_MATVEC 用）
                              CALL COMPUTE_STEADY_RESIDUAL(data_4d137, cellprimitivesout)
! 阻力标量 J
							  print *, "开始计算阻力"
                              ! 阻力标量 J
                              ! 阻力标量 J
                              CALL COMPUTE_DRAG(data_4d137, cellprimitivesout, drag_value)
! 写入模块变量，供 ADJOINT_MATVEC / COMPUTE_DJDP 使用（用 cellprimitivesout 的实际维度，避免与 ncells 不一致导致段错误）
                              IF (ALLOCATED(cellprimitivesout_adj)) DEALLOCATE(cellprimitivesout_adj)
                              IF (ALLOCATED(cellprimitivesoutb_adj)) DEALLOCATE(cellprimitivesoutb_adj)
                              n_adj = SIZE(cellprimitivesout, 1) * SIZE(cellprimitivesout, 2)
                              ALLOCATE(cellprimitivesout_adj(SIZE(cellprimitivesout, 1), SIZE(cellprimitivesout, 2)))
                              ALLOCATE(cellprimitivesoutb_adj(SIZE(cellprimitivesout, 1), SIZE(cellprimitivesout, 2)))
                              cellprimitivesout_adj = cellprimitivesout
                              data_4d137_adj = data_4d137
! b = (∂J/∂w)^T，来自 COMPUTE_DRAG_B，种子 Jb=1
                              data_4d137b(1, 1:4) = 0.0_8
                              cellprimitivesoutb = 0.0_8
                              print *, "开始计算阻力对变形参数和状态变量"
                              ! b = (∂J/∂w)^T，来自 COMPUTE_DRAG_B，种子 Jb=1（必须用变量，不能传常量 1.0_8）
							  jb_seed = 1.0_8
							  CALL COMPUTE_DRAG_B(data_4d137, cellprimitivesout, cellprimitivesoutb, drag_value, jb_seed)
                              print *, "开始计算阻力对变形参数和状态变量1"
                              n_adj = ncells * 5
                              ALLOCATE(b_adj(n_adj), psi_adj(n_adj), dJdp(4))
                              b_adj = RESHAPE(cellprimitivesoutb, [n_adj])
                              dJdp_partial(1:4) = 0.0_8
! JF-GMRES: (∂R/∂w)^T psi = b
                              psi_adj = 0.0_8
                              print *, "反向模式 AD 近似矩阵 - 向量乘（无雅可比矩阵）,GMRES求解伴随值"
                              ! 伴随 GMRES：放宽收敛条件（网格约 18513 单元时 tol=1e-6 过严会迭代过久）
							  CALL SOLVE_ADJOINT_JFGMRES(b_adj, psi_adj, n_adj, 100_8&
, 1.0e+3_8, ADJOINT_MATVEC, niter_adj, resnorm_adj)!1.0e-6_8,1.0e-3_8
                              print *, "求解目标函数对变形参数的梯度"
                              CALL COMPUTE_DJDP(dJdp_partial, psi_adj, dJdp)
                              CALL WRITEOUTPUT_B(cellprimitivesout, 'restart_adjoint.dat', meshpath, .false., .true., point_update&
                              , drag_value, dJdp, dJdp_partial, cellprimitivesoutb)
                              PRINT*, 'dJ/dp = ', dJdp
                              DEALLOCATE(b_adj, psi_adj)
                              DEALLOCATE(cellprimitivesout_adj, cellprimitivesoutb_adj)
                              PRINT*, 'dJ/dp = ', dJdp
!							  CALL COMPUTE_STEADY_RESIDUAL_B(data_4d137, data_4d137b, &
!&   cellPrimitivesout, cellPrimitivesoutb)
! 释放point_update内存        
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                              DEALLOCATE(cellprimitivesout)
                              DEALLOCATE(fluxresiduals)

							deallocate(fluxResidualsb, cellPrimitivesoutb, fluxResiduals_slnb, &
									   cVols_meshb, faceFluxes_slnb, fAVecs_meshb)

							deallocate(eps22b, fDb, unitFAb, diffusionFluxb, fDeltasb, epssb, &
									   cellFluxes_slnb)

							deallocate(cellPrimitives_slnb, cellState_slnb, facePtsb, fCsb, &
									   cell_fAVecsb, points_tempMeshb, point_updateb)

							deallocate(eps4b, eps2b, rjsjFb, p_matrixb, gradPb, temp_gradb, &
									   cCenters_meshb, sjb, rjb, fDGradsb, uunitVecb, &
									   faceValsb, fCenters_meshb)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                              DEALLOCATE(lines_defor)
                              IF (ALLOCATED(inoutput)) THEN
                                DEALLOCATE(inoutput)
                              END IF
                              IF (ALLOCATED(wing)) THEN
                                DEALLOCATE(wing)
                              END IF
                              IF (ALLOCATED(point_update)) THEN
                                DEALLOCATE(point_update)
                              END IF
                              IF (ALLOCATED(points_meshdefor)) THEN
                                DEALLOCATE(points_meshdefor)
                              END IF
                              IF (ALLOCATED(mat_inv)) THEN
                                DEALLOCATE(mat_inv)
                              END IF
                              IF (ALLOCATED(wing_coords)) THEN
                                DEALLOCATE(wing_coords)
                              END IF
                              IF (ALLOCATED(inoutput_coords)) THEN
                                DEALLOCATE(inoutput_coords)
                              END IF
                              IF (ALLOCATED(r_row)) THEN
                                DEALLOCATE(r_row)
                              END IF
                              IF (ALLOCATED(phi_row)) THEN
                                DEALLOCATE(phi_row)
                              END IF
                              IF (ALLOCATED(control_points)) THEN
                                DEALLOCATE(control_points)
                              END IF
                              IF (ALLOCATED(phi)) THEN
                                DEALLOCATE(phi)
                              END IF
                              IF (ALLOCATED(distances)) THEN
                                DEALLOCATE(distances)
                              END IF
!         if (allocated(fluxResidualsOut)) deallocate(fluxResidualsOut)
!		  if (allocated(wing_update)) deallocate(wing_update)
!!!!!!!!!!!! meshdeformation
!!!!!!!!!!!! Buflow
                              DEALLOCATE(currentboundary)
!        deallocate(P_eps)
                              DEALLOCATE(p_matrix)
                              DEALLOCATE(temp_grad)
                              DEALLOCATE(gradp)
                              DEALLOCATE(sj)
                              DEALLOCATE(sjcount)
                              DEALLOCATE(rj)
                              DEALLOCATE(rjsjf)
                              DEALLOCATE(eps2)
                              DEALLOCATE(eps4)
                              DEALLOCATE(facevals)
                              DEALLOCATE(timefluxes)
                              DEALLOCATE(surfaceareas)
                              DEALLOCATE(timefluxess)
                              DEALLOCATE(surfaceareass)
                              DEALLOCATE(facevel)
                              DEALLOCATE(positionn)
                              DEALLOCATE(facerhot)
                              DEALLOCATE(cellrhot)
                              DEALLOCATE(epss)
                              DEALLOCATE(fdeltas)
                              DEALLOCATE(fdgrads)
                              DEALLOCATE(eps22)
                              DEALLOCATE(eps44)
                              DEALLOCATE(diffusionflux)
                              DEALLOCATE(unitfa)
                              DEALLOCATE(fd)
                              DEALLOCATE(farownerfd)
                              DEALLOCATE(farneighbourfd)
                              DEALLOCATE(dt_val)
                              PRINT*, 'Aa'
                              DEALLOCATE(blines)
                              PRINT*, 'c'
!		if (allocated(lines_neighbour)) deallocate(lines_neighbour)
!     	deallocate()
                              PRINT*, 'c'
                              DEALLOCATE(lines_owner)
                              PRINT*, 'Aa'
                              DEALLOCATE(lines_faces)
                              DEALLOCATE(pts_faces)
                              DEALLOCATE(tmp_faces)
                              DEALLOCATE(dt_solve)
!		deallocate(first5_refs(5,3))
                              DEALLOCATE(fcs)
                              DEALLOCATE(cell_favecs)
                              DEALLOCATE(cellpts)
                              DEALLOCATE(cellfacecount)
                              DEALLOCATE(facepts)
                              DEALLOCATE(uunitvec)
                              PRINT*, 'Aa'
!!!!!!!!!!!! Buflow		
                              GOTO 100
                            ELSE
                              nlines_faces = nlines_faces + 1
                            END IF
                          END DO
                        END IF
                      ELSE
                        nlines_neighbour = nlines_neighbour + 1
                      END IF
                    END DO
                  END IF
                ELSE
                  nlines_owner = nlines_owner + 1
                END IF
              END DO
            END IF
          ELSE
            nlines_boundary = nlines_boundary + 1
          END IF
        END DO
      ELSE
        nlines_points = nlines_points + 1
      END IF
    END DO
 100 CONTINUE
  END SUBROUTINE MAIN
  SUBROUTINE ADJOINT_MATVEC(n, v, Av)
    USE TYPESMODULE_DIFF
    IMPLICIT NONE
    INTEGER(kind=8), INTENT(IN) :: n
    REAL(kind=8), INTENT(IN) :: v(n)
    REAL(kind=8), INTENT(OUT) :: Av(n)
    INTEGER(kind=8) :: nc, nv
    IF (.NOT. ALLOCATED(cellprimitivesout_adj)) RETURN
    nc = SIZE(cellprimitivesout_adj, 1)
    nv = SIZE(cellprimitivesout_adj, 2)
    IF (n .NE. nc*nv) RETURN
    fluxresidualsb(1:nc, 1:nv) = RESHAPE(v, [nc, nv])
    data_4d137b_adj = 0.0_8
    cellprimitivesoutb_adj = 0.0_8
    CALL COMPUTE_STEADY_RESIDUAL_B(data_4d137_adj, data_4d137b_adj, cellprimitivesout_adj, cellprimitivesoutb_adj)
    Av = RESHAPE(cellprimitivesoutb_adj, [n])
  END SUBROUTINE ADJOINT_MATVEC

  SUBROUTINE COMPUTE_DJDP(dJdp_partial, psi, dJdp)
    USE TYPESMODULE_DIFF
    IMPLICIT NONE
    REAL(kind=8), INTENT(IN) :: dJdp_partial(4)
    REAL(kind=8), INTENT(IN) :: psi(*)
    REAL(kind=8), INTENT(OUT) :: dJdp(4)
    INTEGER(kind=8) :: nc, nv, n
    IF (.NOT. ALLOCATED(fluxresiduals)) RETURN
    nc = SIZE(fluxresiduals, 1)
    nv = SIZE(fluxresiduals, 2)
    n = nc * nv
    fluxresidualsb(1:nc, 1:nv) = RESHAPE(psi(1:n), [nc, nv])
    data_4d137b_adj = 0.0_8
    cellprimitivesoutb_adj = 0.0_8
    CALL COMPUTE_STEADY_RESIDUAL_B(data_4d137_adj, data_4d137b_adj, cellprimitivesout_adj, cellprimitivesoutb_adj)
    dJdp(1:4) = dJdp_partial(1:4) - data_4d137b_adj(1, 1:4)
  END SUBROUTINE COMPUTE_DJDP

  SUBROUTINE READOPENFOAMMESHH(polymeshpath, tempmesh)
    IMPLICIT NONE
    CHARACTER(len=*), INTENT(IN) :: polymeshpath
    TYPE(MESHDATA), INTENT(OUT) :: tempmesh
    CHARACTER(len=256) :: pointsfilepath, facesfilepath, ownerfilepath, &
&   neighbourfilepath, boundaryfilepath
    INTRINSIC TRIM
    pointsfilepath = TRIM(polymeshpath)//'/points'
    facesfilepath = TRIM(polymeshpath)//'/faces'
    ownerfilepath = TRIM(polymeshpath)//'/owner'
    neighbourfilepath = TRIM(polymeshpath)//'/neighbour'
    boundaryfilepath = TRIM(polymeshpath)//'/boundary'
    CALL READOFPOINTSFILE(pointsfilepath)
    facepoints_tempmesh = READOFFACESFILE(facesfilepath)
    owner_tempmesh = READOFOWNERFILE(ownerfilepath)
    neighbour_tempmesh = READOFNEIGHBOURFILE(neighbourfilepath)
    CALL READOFBOUNDARYFILE(boundaryfilepath, tempmesh%boundarynames, &
&                     tempmesh%boundarynumfaces, tempmesh%&
&                     boundarystartfaces)
  END SUBROUTINE READOPENFOAMMESHH

  SUBROUTINE OFFILE_FINDNITEMSSS(filelines, startline, itemcount)
    IMPLICIT NONE
    CHARACTER(len=*), INTENT(IN) :: filelines(:)
    INTEGER(kind=8), INTENT(OUT) :: startline, itemcount
    INTEGER(kind=8) :: i, pos, iostat
    CHARACTER(len=256) :: line
    INTRINSIC SIZE
    INTRINSIC TRIM
    INTRINSIC INDEX
    itemcount = 0
    startline = 0
    DO i=1,SIZE(filelines)
      line = TRIM(filelines(i))
      pos = INDEX(line, 'nPoints') + INDEX(line, 'nFaces') + INDEX(line&
&       , 'size')
      IF (pos .NE. 0) THEN
        READ(line(pos:), *, iostat=iostat) itemcount
        IF (itemcount .GT. 0) THEN
          startline = i + 2
          RETURN
        END IF
      END IF
    END DO
    DO i=1,SIZE(filelines)
      IF (ISNUMBERRR(TRIM(filelines(i)))) THEN
        READ(filelines(i), *, iostat=iostat) itemcount
        IF (itemcount .GT. 0) THEN
          startline = i + 2
          RETURN
        END IF
      END IF
    END DO
    DO i=1,SIZE(filelines)
      IF (INDEX(filelines(i), '(') .GT. 0) THEN
        startline = i + 1
        GOTO 100
      END IF
    END DO
 100 itemcount = 0
    DO i=startline,SIZE(filelines)
      IF (INDEX(filelines(i), ')') .GT. 0) THEN
        GOTO 110
      ELSE
        itemcount = itemcount + 1
      END IF
    END DO
 110 CONTINUE
  END SUBROUTINE OFFILE_FINDNITEMSSS

  LOGICAL FUNCTION ISNUMBERRR(str)
    IMPLICIT NONE
    CHARACTER(len=*), INTENT(IN) :: str
    REAL(kind=8) :: num
    INTEGER(kind=8) :: iostat
    isnumberrr = .false.
    READ(str, *, iostat=iostat) num
    IF (iostat .EQ. 0) isnumberrr = .true.
  END FUNCTION ISNUMBERRR

END MODULE MAIN_MODULE_DIFF

