!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 29 Jul 2025 17:17
!
MODULE MESHDEFORMATIONN_DIFF
!	use iso_fortran_env
  USE TYPESMODULE_DIFF
! 2. 再禁用默认类型
! 仅 Tapenade 处理时取消注释（原代码编译时注释掉）
!include 'tapenade_includes.f90'  ! <<< 仅 Tapenade 用，原编译时注释
!非tapenade时call move_alloc_char(originalLines, newLines)
  IMPLICIT NONE

CONTAINS
!  Differentiation of airfoil_deformation_hh in reverse (adjoint) mode (with options noISIZE i4 dr8 r4):
!   gradient     of useful results: *point_update
!   with respect to varying inputs: data_4d137
!   Plus diff mem management of: point_update:in
  SUBROUTINE AIRFOIL_DEFORMATION_HH_B(data_4d137, data_4d137b)
    IMPLICIT NONE
    REAL*8, ALLOCATABLE :: wing_update(:, :)
    REAL*8, ALLOCATABLE :: wing_updateb(:, :)
    REAL*8, INTENT(IN) :: data_4d137(1, 4)!原代码REAL*8, INTENT(IN) :: data_4d137(:, :)
    REAL*8 :: data_4d137b(1, 4)!原代码REAL*8 :: data_4d137b(:, :)
!		real*8, allocatable, intent(inout) :: point_update(:,:) 
    REAL*8 :: rae2822_up(50, 2), rae2822_low(50, 2)
    REAL*8 :: x1(50), y_up(50), y_low(50), loca(2), xx(2), fun1_result(&
&   50), funk_result(50)
    REAL*8 :: s(100, 4), s_up(100, 2), s_low(100, 2)
    REAL*8 :: sb(100, 4), s_upb(100, 2), s_lowb(100, 2)
    REAL*8 :: f_up(50), f_low(50), yy_up(50), yy_low(50)
    REAL*8 :: f_upb(50), f_lowb(50), yy_upb(50), yy_lowb(50)
    REAL*8 :: avg_y_51
    REAL*8 :: avg_y_51b
    REAL*8 :: up_part(49, 2), row_51(2), low_part(49, 2)
    REAL*8 :: up_partb(49, 2), row_51b(2), low_partb(49, 2)
    INTEGER :: d, n, i, k
    INTRINSIC SIZE
    INTRINSIC COS
    INTRINSIC ALLOCATED
    INTEGER :: ad_to
    INTEGER :: ad_to0
!		real*8, allocatable :: wing(:,:), inoutput(:,:)
!        allocate(inoutput(99, 2), source=0.0_real64)
!        allocate(wing(99, 2), source=0.0_real64)
	print *,"AW"
    ALLOCATE(wing_updateb(99, 2), source=0.0_real64)
    wing_updateb = 0.0_8
    ALLOCATE(wing_update(99, 2), source=0.0_real64)
! 1. 提取输入输出边界点（初始化inoutput）
    inoutput = CSV_READ('boundary_inoutput_xy.csv')
! 从文件读取翼型数据
    wing = CSV_READ('wing.csv')
! 提取上表面坐标
    rae2822_up = wing(1:50, :)
! 提取下表面坐标
! 提取坐标向量
    x1 = rae2822_up(:, 1)
! 处理变形参数
    d = SIZE(data_4d137, 2)
    DO i=1,d
      DO k=1,SIZE(data_4d137, 1)

      END DO
      CALL PUSHINTEGER4(k - 1)
    END DO
    CALL PUSHINTEGER4(i - 1)
    n = SIZE(s_up, 1)
! 计算变形
    IF (n .GT. 0) THEN
! 计算变形函数
! 第二个参数 50 是 x1 的长度
      CALL FUN1(x1, 50, fun1_result)
! 第二个参数 50 是 X（即 x1）的长度
      CALL FUNK(x1, 50, 2, funk_result)
! 特殊处理重叠点
! 构建更新后的翼型
! 合并三部分
! 输出到文件
! 释放临时分配的内存
!		if (allocated(inoutput)) deallocate(inoutput)
!		if (allocated(wing)) deallocate(wing)
	  print *,"AW"				
      CALL MESHDEFORMATION_B(wing_update, wing_updateb)
      low_partb = 0.0_8
      low_partb = wing_updateb(51:99, :)
      wing_updateb(51:99, :) = 0.0_8
      row_51b = 0.0_8
      row_51b = wing_updateb(50, :)
      wing_updateb(50, :) = 0.0_8
      up_partb = 0.0_8
      up_partb = wing_updateb(1:49, :)
      yy_lowb = 0.0_8
      yy_lowb(2:50) = yy_lowb(2:50) + low_partb(:, 2)
      avg_y_51b = row_51b(2)
      yy_upb = 0.0_8
      yy_upb(1:49) = yy_upb(1:49) + up_partb(:, 2)
      yy_upb(50) = yy_upb(50) + avg_y_51b/2.0_8
      yy_lowb(1) = yy_lowb(1) + avg_y_51b/2.0_8
      f_lowb = 0.0_8
      f_lowb = yy_lowb
      f_upb = 0.0_8
      f_upb = yy_upb
      s_lowb = 0.0_8
      s_lowb(1, 1) = s_lowb(1, 1) + SUM(fun1_result*f_lowb)
      s_lowb(1, 2) = s_lowb(1, 2) + SUM(funk_result*f_lowb)
      s_upb = 0.0_8
      s_upb(1, 1) = s_upb(1, 1) + SUM(fun1_result*f_upb)
      s_upb(1, 2) = s_upb(1, 2) + SUM(funk_result*f_upb)
      sb = 0.0_8
      sb(:, 3:4) = sb(:, 3:4) + s_lowb
      sb(:, 1:2) = sb(:, 1:2) + s_upb
      data_4d137b = 0.0_8
      print *,"AW"
      CALL POPINTEGER4(ad_to0)
      !print *,"HH"
      DO i=ad_to0,1,-1
      	!print *,"HH"
        CALL POPINTEGER4(ad_to)
        DO k=ad_to,1,-1
          print *,"HH"
          data_4d137b(k, i) = data_4d137b(k, i) + 3.1415926535_8*SIN(&
&           3.1415926535_8*((1.0_8-data_4d137(k, i))/2.0_8))*0.05_8*sb(k&
&           , i)/2.0_8
		  print *,"HH"
          sb(k, i) = 0.0_8
        END DO
      END DO
      print *,"AW"
      DEALLOCATE(wing_update)
      DEALLOCATE(wing_updateb)
    ELSE
      STOP
    END IF

  CONTAINS
! 变形函数fun1
! 新增 n：x 的长度（显式维度）
    SUBROUTINE FUN1(x, n, result)
      IMPLICIT NONE
! 数组 x 的维度（如 50）
      INTEGER, INTENT(IN) :: n
! 用 n 声明 x 的维度
      REAL*8, INTENT(IN) :: x(n)
! 用 n 声明 result 的维度（与 x 一致）
      REAL*8, INTENT(OUT) :: result(n)
      INTRINSIC EXP
      result = x**0.25_8*(1.0_8-x)*EXP(-(20.0_8*x))
    END SUBROUTINE FUN1

! 变形函数funk
! 新增 n：X 的长度（显式维度）
    SUBROUTINE FUNK(x, n, k, result)
      IMPLICIT NONE
! 数组 X 的维度（如 50）
      INTEGER, INTENT(IN) :: n
! 用 n 声明 X 的维度
      REAL*8, INTENT(IN) :: x(n)
      INTEGER, INTENT(IN) :: k
! 用 n 声明 result 的维度
      REAL*8, INTENT(OUT) :: result(n)
      REAL*8 :: xxx(2), ee
      INTRINSIC LOG10
      INTRINSIC SIN
      xxx = (/x1(1), x1(8)/)
      ee = LOG10(0.5_8)/LOG10(xxx(k))
      result = SIN(3.1415926535_8*x**ee)**3
    END SUBROUTINE FUNK

  END SUBROUTINE AIRFOIL_DEFORMATION_HH_B

  SUBROUTINE AIRFOIL_DEFORMATION_HH(data_4d137)
    IMPLICIT NONE
    REAL*8, ALLOCATABLE :: wing_update(:, :)
    REAL*8, INTENT(IN) :: data_4d137(:, :)
!		real*8, allocatable, intent(inout) :: point_update(:,:) 
    REAL*8 :: rae2822_up(50, 2), rae2822_low(50, 2)
    REAL*8 :: x1(50), y_up(50), y_low(50), loca(2), xx(2), fun1_result(&
&   50), funk_result(50)
    REAL*8 :: s(100, 4), s_up(100, 2), s_low(100, 2)
    REAL*8 :: f_up(50), f_low(50), yy_up(50), yy_low(50)
    REAL*8 :: avg_y_51
    REAL*8 :: up_part(49, 2), row_51(2), low_part(49, 2)
    INTEGER :: d, n, i, k
    INTRINSIC SIZE
    INTRINSIC COS
    INTRINSIC ALLOCATED
!		real*8, allocatable :: wing(:,:), inoutput(:,:)
!        allocate(inoutput(99, 2), source=0.0_real64)
!        allocate(wing(99, 2), source=0.0_real64)
    ALLOCATE(wing_update(99, 2), source=0.0_real64)
! 1. 提取输入输出边界点（初始化inoutput）
    inoutput = CSV_READ('boundary_inoutput_xy.csv')
! 从文件读取翼型数据
    wing = CSV_READ('wing.csv')
! 提取上表面坐标
    rae2822_up = wing(1:50, :)
! 提取下表面坐标
    rae2822_low = wing(50:99, :)
! 提取坐标向量
    x1 = rae2822_up(:, 1)
    y_up = rae2822_up(:, 2)
    y_low = rae2822_low(:, 2)
    loca = (/1.0_8, 8.0_8/)
    xx = (/x1(1), x1(8)/)
! 处理变形参数
    d = SIZE(data_4d137, 2)
    s = 0.0_8
    DO i=1,d
      DO k=1,SIZE(data_4d137, 1)
        s(k, i) = 0.05_8*COS((1.0_8-data_4d137(k, i))/2.0_8*&
&         3.1415926535_8)
      END DO
    END DO
    s_up = s(:, 1:2)
    s_low = s(:, 3:4)
    n = SIZE(s_up, 1)
! 计算变形
    IF (n .GT. 0) THEN
! 计算变形函数
! 第二个参数 50 是 x1 的长度
      CALL FUN1(x1, 50, fun1_result)
! 第二个参数 50 是 X（即 x1）的长度
      CALL FUNK(x1, 50, 2, funk_result)
      f_up = fun1_result*s_up(1, 1) + funk_result*s_up(1, 2)
      f_low = fun1_result*s_low(1, 1) + funk_result*s_low(1, 2)
      yy_up = y_up + f_up
      yy_low = y_low + f_low
! 特殊处理重叠点
      avg_y_51 = (yy_up(50)+yy_low(1))/2.0_8
! 构建更新后的翼型
      up_part(:, 1) = x1(1:49)
      up_part(:, 2) = yy_up(1:49)
      row_51(1) = x1(50)
      row_51(2) = avg_y_51
      low_part(:, 1) = rae2822_low(2:50, 1)
      low_part(:, 2) = yy_low(2:50)
! 合并三部分
      wing_update(1:49, :) = up_part
      wing_update(50, :) = row_51
      wing_update(51:99, :) = low_part
! 输出到文件
      CALL CSV_WRITE('wing_update.csv', wing_update, 99, 2)
      PRINT*, '翼型坐标已更新并保存至wing_update.csv'
! 释放临时分配的内存
!		if (allocated(inoutput)) deallocate(inoutput)
!		if (allocated(wing)) deallocate(wing)				
      CALL MESHDEFORMATION(wing_update)
      IF (ALLOCATED(wing_update)) THEN
        DEALLOCATE(wing_update)
      END IF
    ELSE
      PRINT*, '错误：无变形参数可用'
      STOP
    END IF
    PRINT*, 'aAd'

  CONTAINS
! 变形函数fun1
! 新增 n：x 的长度（显式维度）
    SUBROUTINE FUN1(x, n, result)
      IMPLICIT NONE
! 数组 x 的维度（如 50）
      INTEGER, INTENT(IN) :: n
! 用 n 声明 x 的维度
      REAL*8, INTENT(IN) :: x(n)
! 用 n 声明 result 的维度（与 x 一致）
      REAL*8, INTENT(OUT) :: result(n)
      INTRINSIC EXP
      result = x**0.25_8*(1.0_8-x)*EXP(-(20.0_8*x))
    END SUBROUTINE FUN1

! 变形函数funk
! 新增 n：X 的长度（显式维度）
    SUBROUTINE FUNK(x, n, k, result)
      IMPLICIT NONE
! 数组 X 的维度（如 50）
      INTEGER, INTENT(IN) :: n
! 用 n 声明 X 的维度
      REAL*8, INTENT(IN) :: x(n)
      INTEGER, INTENT(IN) :: k
! 用 n 声明 result 的维度
      REAL*8, INTENT(OUT) :: result(n)
      REAL*8 :: xxx(2), ee
      INTRINSIC LOG10
      INTRINSIC SIN
      xxx = (/x1(1), x1(8)/)
      ee = LOG10(0.5_8)/LOG10(xxx(k))
      result = SIN(3.1415926535_8*x**ee)**3
    END SUBROUTINE FUNK

  END SUBROUTINE AIRFOIL_DEFORMATION_HH

!  Differentiation of meshdeformation in reverse (adjoint) mode (with options noISIZE i4 dr8 r4):
!   gradient     of useful results: *point_update
!   with respect to varying inputs: [alloc*wing_update in airfoil_deformation_hh]
!   Plus diff mem management of: point_update:in wing_update:in
  SUBROUTINE MESHDEFORMATION_B(wing_update, wing_updateb)
    IMPLICIT NONE
    CHARACTER(len=256) :: meshpath
    REAL*8, ALLOCATABLE, INTENT(IN) :: wing_update(:, :)
    REAL*8, ALLOCATABLE :: wing_updateb(:, :)
!        real*8, allocatable, intent(inout) :: point_update(:,:) 
    CHARACTER(len=256) :: pointsfilepath
!		real(kind=8), allocatable :: points(:,:), mat_inv(:,:)
    INTEGER :: npoints, nwing, ninoutput, ncontrol, i, j, k, pt, line, &
&   iostat, len_str, linecount
!		real(kind=8), allocatable :: wing_coords(:,:), inoutput_coords(:,:), r_row(:), phi_row(:)
    REAL(kind=8), ALLOCATABLE :: wing_update_coords(:, :), d_wing_x(:), &
&   d_wing_y(:), d_inoutput_x(:), d_inoutput_y(:), weights_x(:), &
&   weights_y(:)
    REAL(kind=8), ALLOCATABLE :: wing_update_coordsb(:, :), d_wing_xb(:)&
&   , d_wing_yb(:), weights_xb(:), weights_yb(:)
!		real(kind=8), allocatable :: control_points(:,:)
    REAL(kind=8), ALLOCATABLE :: d_control_x(:), d_control_y(:), &
&   d_mesh_x(:), d_mesh_y(:), d_mesh_z(:)
    REAL(kind=8), ALLOCATABLE :: d_control_xb(:), d_control_yb(:), &
&   d_mesh_xb(:), d_mesh_yb(:)
!		real(kind=8), allocatable :: phi(:,:), distances(:)
    REAL(kind=8) :: epsilonn, diff(2), r, x, y, z, d_nomal
    CHARACTER(len=256), ALLOCATABLE :: originallines(:), newdatalines(:)&
&   , newlines(:)
    INTEGER :: nline, datastartline
    INTRINSIC TRIM
    INTRINSIC SIZE
    INTRINSIC SUM
    INTRINSIC SQRT
    INTRINSIC ALLOCATED
    INTEGER*4 :: branch
!		real*8, allocatable :: wing(:,:), inoutput(:,:)
    meshpath = 'mesh/OFairfoilMesh'
    pointsfilepath = TRIM(meshpath)//'/points'
!		allocate(points(37254,3), source=0.0_8)  ! 空数组初始化
    points_meshdefor = READOFPOINTSFILEF(pointsfilepath)
    npoints = SIZE(points_meshdefor, 1)
!        if (.not. allocated(wing)) allocate(wing(99, 2), source=0.0_real64)
!		if (.not. allocated(inoutput)) allocate(inoutput(99, 2), source=0.0_real64)
    inoutput = CSV_READ('boundary_inoutput_xy.csv')
    wing = CSV_READ('wing.csv')
    nwing = SIZE(wing_update, 1)
    ninoutput = SIZE(inoutput, 1)
!		allocate(wing_coords(nWing,2), wing_update_coords(nWing,2), inoutput_coords(nInoutput,2))
    ALLOCATE(wing_update_coordsb(nwing, 2))
    wing_update_coordsb = 0.0_8
    ALLOCATE(wing_update_coords(nwing, 2))
    ncontrol = nwing + ninoutput
!		allocate(control_points(nControl,2))
    control_points(1:nwing, :) = wing
    control_points(nwing+1:ncontrol, :) = inoutput
    ALLOCATE(d_wing_xb(nwing))
    d_wing_xb = 0.0_8
    ALLOCATE(d_wing_x(nwing))
    ALLOCATE(d_wing_yb(nwing))
    d_wing_yb = 0.0_8
    ALLOCATE(d_wing_y(nwing))
    ALLOCATE(d_inoutput_x(ninoutput))
    ALLOCATE(d_inoutput_y(ninoutput))
    ALLOCATE(d_control_xb(ncontrol))
    d_control_xb = 0.0_8
    ALLOCATE(d_control_x(ncontrol))
    ALLOCATE(d_control_yb(ncontrol))
    d_control_yb = 0.0_8
    ALLOCATE(d_control_y(ncontrol))
    ALLOCATE(d_mesh_xb(npoints))
    d_mesh_xb = 0.0_8
    ALLOCATE(d_mesh_x(npoints))
    ALLOCATE(d_mesh_yb(npoints))
    d_mesh_yb = 0.0_8
    ALLOCATE(d_mesh_y(npoints))
    ALLOCATE(d_mesh_z(npoints))
!		allocate(r_row(nControl), phi_row(nControl))
!		allocate(phi(nControl, nControl))
    DO j=1,ncontrol
      DO k=1,ncontrol
        diff = control_points(j, :) - control_points(k, :)
        r_row(k) = SQRT(SUM(diff**2))
      END DO
      CALL GAUSSIAN_RBF_ARRAY(r_row, epsilonn, phi_row(1:ncontrol), &
&                       ncontrol)
      phi(j, :) = phi_row
    END DO
    ALLOCATE(weights_xb(ncontrol), source=0.0_8)
    weights_xb = 0.0_8
    ALLOCATE(weights_x(ncontrol), source=0.0_8)
! 预初始化
    ALLOCATE(weights_yb(ncontrol), source=0.0_8)
    weights_yb = 0.0_8
    ALLOCATE(weights_y(ncontrol), source=0.0_8)
!		allocate(mat_inv(nControl, nControl), source=0.0_8)
! 2. 调用简化版 inverse（仅传 3 个参数，无 info_out）
    CALL INVERSE(ncontrol, phi, mat_inv)
! 3. 矩阵乘法（用 mat_inv 替代原 inverse(phi)，维度明确）
! 4. 释放逆矩阵（用完即释，避免内存占用）
!		allocate(distances(nControl))
    DO pt=1,npoints
      DO j=1,ncontrol
        diff = points_meshdefor(pt, 1:2) - control_points(j, :)
        distances(j) = SQRT(SUM(diff**2))
      END DO
      IF (ALLOCATED(phi_row)) THEN
        CALL PUSHREAL8ARRAY(phi_row(1:ncontrol), ncontrol)
        CALL PUSHCONTROL1B(1)
      ELSE
        CALL PUSHCONTROL1B(0)
      END IF
      CALL GAUSSIAN_RBF_ARRAY(distances, epsilonn, phi_row(1:ncontrol), &
&                       ncontrol)
!计算网格点的位移d_mesh_x,d_mesh_y
    END DO
    DO pt=npoints,1,-1
      d_mesh_yb(pt) = d_mesh_yb(pt) + point_updateb(pt, 2)
      d_mesh_xb(pt) = d_mesh_xb(pt) + point_updateb(pt, 1)
    END DO
    DO pt=npoints,1,-1
      CALL DOT_PRODUCT_REALLL_B(weights_y, weights_yb, phi_row, d_mesh_y&
&                         (pt), d_mesh_yb(pt))
      d_mesh_yb(pt) = 0.0_8
      CALL DOT_PRODUCT_REALLL_B(weights_x, weights_xb, phi_row, d_mesh_x&
&                         (pt), d_mesh_xb(pt))
      d_mesh_xb(pt) = 0.0_8
      CALL POPCONTROL1B(branch)
      IF (branch .EQ. 1) CALL POPREAL8ARRAY(phi_row(1:ncontrol), &
&                                     ncontrol)
    END DO
    CALL MATMUL_REAL_B(mat_inv, d_control_y, d_control_yb, weights_y, &
&                weights_yb)
    weights_yb = 0.0_8
    CALL MATMUL_REAL_B(mat_inv, d_control_x, d_control_xb, weights_x, &
&                weights_xb)
    weights_xb = 0.0_8
    DEALLOCATE(weights_y)
    DEALLOCATE(weights_yb)
    DEALLOCATE(weights_x)
    DEALLOCATE(weights_xb)
    DEALLOCATE(d_mesh_z)
    DEALLOCATE(d_mesh_y)
    DEALLOCATE(d_mesh_yb)
    DEALLOCATE(d_mesh_x)
    DEALLOCATE(d_mesh_xb)
    d_control_yb(nwing+1:ncontrol) = 0.0_8
    IF (ALLOCATED(d_wing_yb)) d_wing_yb = 0.0_8
    d_wing_yb = d_wing_yb + d_control_yb(1:nwing)
    d_control_xb(nwing+1:ncontrol) = 0.0_8
    IF (ALLOCATED(d_wing_xb)) d_wing_xb = 0.0_8
    d_wing_xb = d_wing_xb + d_control_xb(1:nwing)
    DEALLOCATE(d_control_y)
    DEALLOCATE(d_control_yb)
    DEALLOCATE(d_control_x)
    DEALLOCATE(d_control_xb)
    DEALLOCATE(d_inoutput_y)
    DEALLOCATE(d_inoutput_x)
    IF (ALLOCATED(wing_update_coordsb)) wing_update_coordsb = 0.0_8
    wing_update_coordsb(:, 2) = wing_update_coordsb(:, 2) + d_wing_yb
    wing_update_coordsb(:, 1) = wing_update_coordsb(:, 1) + d_wing_xb
    DEALLOCATE(d_wing_y)
    DEALLOCATE(d_wing_yb)
    DEALLOCATE(d_wing_x)
    DEALLOCATE(d_wing_xb)
    IF (ALLOCATED(wing_updateb)) wing_updateb = 0.0_8
    wing_updateb = wing_updateb + wing_update_coordsb
    DEALLOCATE(wing_update_coords)
    DEALLOCATE(wing_update_coordsb)
  END SUBROUTINE MESHDEFORMATION_B

  SUBROUTINE MESHDEFORMATION(wing_update)
    IMPLICIT NONE
    CHARACTER(len=256) :: meshpath
    REAL*8, ALLOCATABLE, INTENT(IN) :: wing_update(:, :)
!        real*8, allocatable, intent(inout) :: point_update(:,:) 
    CHARACTER(len=256) :: pointsfilepath
!		real(kind=8), allocatable :: points(:,:), mat_inv(:,:)
    INTEGER :: npoints, nwing, ninoutput, ncontrol, i, j, k, pt, line, &
&   iostat, len_str, linecount
!		real(kind=8), allocatable :: wing_coords(:,:), inoutput_coords(:,:), r_row(:), phi_row(:)
    REAL(kind=8), ALLOCATABLE :: wing_update_coords(:, :), d_wing_x(:), &
&   d_wing_y(:), d_inoutput_x(:), d_inoutput_y(:), weights_x(:), &
&   weights_y(:)
!		real(kind=8), allocatable :: control_points(:,:)
    REAL(kind=8), ALLOCATABLE :: d_control_x(:), d_control_y(:), &
&   d_mesh_x(:), d_mesh_y(:), d_mesh_z(:)
!		real(kind=8), allocatable :: phi(:,:), distances(:)
    REAL(kind=8) :: epsilonn, diff(2), r, x, y, z, d_nomal
    CHARACTER(len=256), ALLOCATABLE :: originallines(:), newdatalines(:)&
&   , newlines(:)
    INTEGER :: nline, datastartline
    INTRINSIC TRIM
    INTRINSIC SIZE
    INTRINSIC SUM
    INTRINSIC SQRT
    INTRINSIC ALLOCATED
!		real*8, allocatable :: wing(:,:), inoutput(:,:)
    PRINT*, 'aAa'
    meshpath = 'mesh/OFairfoilMesh'
    pointsfilepath = TRIM(meshpath)//'/points'
!		allocate(points(37254,3), source=0.0_8)  ! 空数组初始化
    points_meshdefor = READOFPOINTSFILEF(pointsfilepath)
    npoints = SIZE(points_meshdefor, 1)
!        if (.not. allocated(wing)) allocate(wing(99, 2), source=0.0_real64)
!		if (.not. allocated(inoutput)) allocate(inoutput(99, 2), source=0.0_real64)
    inoutput = CSV_READ('boundary_inoutput_xy.csv')
    wing = CSV_READ('wing.csv')
    nwing = SIZE(wing_update, 1)
    ninoutput = SIZE(inoutput, 1)
!		allocate(wing_coords(nWing,2), wing_update_coords(nWing,2), inoutput_coords(nInoutput,2))
    ALLOCATE(wing_update_coords(nwing, 2))
    wing_coords = wing
    wing_update_coords = wing_update
    inoutput_coords = inoutput
    ncontrol = nwing + ninoutput
!		allocate(control_points(nControl,2))
    control_points(1:nwing, :) = wing
    control_points(nwing+1:ncontrol, :) = inoutput
    ALLOCATE(d_wing_x(nwing))
    ALLOCATE(d_wing_y(nwing))
    d_wing_x = wing_update_coords(:, 1) - wing_coords(:, 1)
    d_wing_y = wing_update_coords(:, 2) - wing_coords(:, 2)
    ALLOCATE(d_inoutput_x(ninoutput))
    ALLOCATE(d_inoutput_y(ninoutput))
    d_inoutput_x = 0.0_8
    d_inoutput_y = 0.0_8
    ALLOCATE(d_control_x(ncontrol))
    ALLOCATE(d_control_y(ncontrol))
    d_control_x(1:nwing) = d_wing_x
    d_control_x(nwing+1:ncontrol) = d_inoutput_x
    d_control_y(1:nwing) = d_wing_y
    d_control_y(nwing+1:ncontrol) = d_inoutput_y
    d_nomal = 1.0_8/4.5_8
    epsilonn = 0.9560721680067801_8
    ALLOCATE(d_mesh_x(npoints))
    ALLOCATE(d_mesh_y(npoints))
    ALLOCATE(d_mesh_z(npoints))
    d_mesh_x = 0.0_8
    d_mesh_y = 0.0_8
    d_mesh_z = 0.0_8
!		allocate(r_row(nControl), phi_row(nControl))
!		allocate(phi(nControl, nControl))
    DO j=1,ncontrol
      DO k=1,ncontrol
        diff = control_points(j, :) - control_points(k, :)
        r_row(k) = SQRT(SUM(diff**2))
      END DO
      CALL GAUSSIAN_RBF_ARRAY(r_row, epsilonn, phi_row(1:ncontrol), &
&                       ncontrol)
      phi(j, :) = phi_row
    END DO
    ALLOCATE(weights_x(ncontrol), source=0.0_8)
! 预初始化
    ALLOCATE(weights_y(ncontrol), source=0.0_8)
!		allocate(mat_inv(nControl, nControl), source=0.0_8)
! 2. 调用简化版 inverse（仅传 3 个参数，无 info_out）
    CALL INVERSE(ncontrol, phi, mat_inv)
! 3. 矩阵乘法（用 mat_inv 替代原 inverse(phi)，维度明确）
    CALL MATMUL_REAL(mat_inv, d_control_x, weights_x)
    CALL MATMUL_REAL(mat_inv, d_control_y, weights_y)
! 4. 释放逆矩阵（用完即释，避免内存占用）
!		allocate(distances(nControl))
    DO pt=1,npoints
      DO j=1,ncontrol
        diff = points_meshdefor(pt, 1:2) - control_points(j, :)
        distances(j) = SQRT(SUM(diff**2))
      END DO
      CALL GAUSSIAN_RBF_ARRAY(distances, epsilonn, phi_row(1:ncontrol), &
&                       ncontrol)
!计算网格点的位移d_mesh_x,d_mesh_y
      CALL DOT_PRODUCT_REALLL(weights_x, phi_row, d_mesh_x(pt))
      CALL DOT_PRODUCT_REALLL(weights_y, phi_row, d_mesh_y(pt))
    END DO
    point_update = points_meshdefor
    DO pt=1,npoints
      point_update(pt, 1) = point_update(pt, 1) + d_mesh_x(pt)
      point_update(pt, 2) = point_update(pt, 2) + d_mesh_y(pt)
    END DO
    PRINT*, 'aAb'
    IF (ALLOCATED(d_wing_x)) THEN
      DEALLOCATE(d_wing_x)
    END IF
    IF (ALLOCATED(d_wing_y)) THEN
      DEALLOCATE(d_wing_y)
    END IF
    IF (ALLOCATED(d_inoutput_x)) THEN
      DEALLOCATE(d_inoutput_x)
    END IF
    IF (ALLOCATED(d_inoutput_y)) THEN
      DEALLOCATE(d_inoutput_y)
    END IF
    IF (ALLOCATED(d_control_x)) THEN
      DEALLOCATE(d_control_x)
    END IF
    IF (ALLOCATED(d_control_y)) THEN
      DEALLOCATE(d_control_y)
    END IF
    IF (ALLOCATED(d_mesh_x)) THEN
      DEALLOCATE(d_mesh_x)
    END IF
    IF (ALLOCATED(d_mesh_y)) THEN
      DEALLOCATE(d_mesh_y)
    END IF
    IF (ALLOCATED(d_mesh_z)) THEN
      DEALLOCATE(d_mesh_z)
    END IF
    IF (ALLOCATED(weights_x)) THEN
      DEALLOCATE(weights_x)
    END IF
    IF (ALLOCATED(weights_y)) THEN
      DEALLOCATE(weights_y)
    END IF
    IF (ALLOCATED(originallines)) THEN
      DEALLOCATE(originallines)
    END IF
    IF (ALLOCATED(newdatalines)) THEN
      DEALLOCATE(newdatalines)
    END IF
    IF (ALLOCATED(newlines)) THEN
      DEALLOCATE(newlines)
    END IF
    PRINT*, 'aAc'
  END SUBROUTINE MESHDEFORMATION

!  Differentiation of matmul_real in reverse (adjoint) mode (with options noISIZE i4 dr8 r4):
!   gradient     of useful results: c
!   with respect to varying inputs: b
! 矩阵×向量乘法子程序：C = A * B（A: m×k 二维矩阵, B: k 一维向量, C: m 一维向量）
  SUBROUTINE MATMUL_REAL_B(a, b, bb, c, cb)
    IMPLICIT NONE
! 输入：A为二维矩阵（m行k列），B为一维向量（长度k）
    REAL*8, INTENT(IN) :: a(:, :), b(:)
    REAL*8 :: bb(:)
! 输出：C为一维向量（长度m，与A的行数一致）
    REAL*8 :: c(:)
    REAL*8 :: cb(:)
! 局部变量：矩阵/向量维度、循环变量
    INTEGER :: m, k, i, l
    INTRINSIC SIZE
! 初始化结果向量为0
! 获取维度并检查合法性
! A的行数（结果C的长度必须等于m）
    m = SIZE(a, 1)
! A的列数（必须等于B的长度）
    k = SIZE(a, 2)
! 检查维度匹配：A的列数 = B的长度
    IF (k .NE. SIZE(b)) THEN
      STOP
    ELSE IF (SIZE(c) .NE. m) THEN
! 检查结果C的长度 = A的行数
      STOP
    ELSE
      bb = 0.0_8
      DO i=m,1,-1
        DO l=k,1,-1
          bb(l) = bb(l) + a(i, l)*cb(i)
        END DO
      END DO
    END IF
  END SUBROUTINE MATMUL_REAL_B

! 矩阵×向量乘法子程序：C = A * B（A: m×k 二维矩阵, B: k 一维向量, C: m 一维向量）
  SUBROUTINE MATMUL_REAL(a, b, c)
    IMPLICIT NONE
! 输入：A为二维矩阵（m行k列），B为一维向量（长度k）
    REAL*8, INTENT(IN) :: a(:, :), b(:)
! 输出：C为一维向量（长度m，与A的行数一致）
    REAL*8, INTENT(OUT) :: c(:)
! 局部变量：矩阵/向量维度、循环变量
    INTEGER :: m, k, i, l
    INTRINSIC SIZE
! 初始化结果向量为0
    c = 0.0_8
! 获取维度并检查合法性
! A的行数（结果C的长度必须等于m）
    m = SIZE(a, 1)
! A的列数（必须等于B的长度）
    k = SIZE(a, 2)
! 检查维度匹配：A的列数 = B的长度
    IF (k .NE. SIZE(b)) THEN
      WRITE(*, *) 'Error in matmul_real: A列数（', k, &
&     '）≠ B长度（', SIZE(b), '）'
      STOP
    ELSE IF (SIZE(c) .NE. m) THEN
! 检查结果C的长度 = A的行数
      WRITE(*, *) 'Error in matmul_real: C长度（', SIZE(c), &
&     '）≠ A行数（', m, '）'
      STOP
    ELSE
! 矩阵×向量乘法核心逻辑（m×k 乘 k×1 = m×1）
! 遍历A的每一行（结果C的每个元素）
      DO i=1,m
! 遍历A的列/B的元素（累加求和）
        DO l=1,k
          c(i) = c(i) + a(i, l)*b(l)
        END DO
      END DO
    END IF
  END SUBROUTINE MATMUL_REAL

!  Differentiation of dot_product_realll in reverse (adjoint) mode (with options noISIZE i4 dr8 r4):
!   gradient     of useful results: result a
!   with respect to varying inputs: a
! 向量点积子程序：result = A · B（A和B需等长）
  SUBROUTINE DOT_PRODUCT_REALLL_B(a, ab, b, result, resultb)
    IMPLICIT NONE
! 输入参数：两个待做点积的向量（real*8 类型）
    REAL*8, INTENT(IN) :: a(:), b(:)
    REAL*8 :: ab(:)
! 输出参数：点积结果（标量）
    REAL*8 :: result
    REAL*8 :: resultb
! 局部变量：向量长度、循环变量
    INTEGER :: len_a, len_b, i
    INTRINSIC SIZE
! 1. 获取向量长度并检查合法性（点积要求两向量等长）
    len_a = SIZE(a)
    len_b = SIZE(b)
    IF (len_a .NE. len_b) THEN
! 终止程序，避免错误计算
      STOP
    ELSE
      DO i=len_a,1,-1
        ab(i) = ab(i) + b(i)*resultb
      END DO
    END IF
  END SUBROUTINE DOT_PRODUCT_REALLL_B

! 向量点积子程序：result = A · B（A和B需等长）
  SUBROUTINE DOT_PRODUCT_REALLL(a, b, result)
    IMPLICIT NONE
! 输入参数：两个待做点积的向量（real*8 类型）
    REAL*8, INTENT(IN) :: a(:), b(:)
! 输出参数：点积结果（标量）
    REAL*8, INTENT(OUT) :: result
! 局部变量：向量长度、循环变量
    INTEGER :: len_a, len_b, i
    INTRINSIC SIZE
! 1. 获取向量长度并检查合法性（点积要求两向量等长）
    len_a = SIZE(a)
    len_b = SIZE(b)
    IF (len_a .NE. len_b) THEN
      WRITE(*, *) 'Error in dot_product_real: 向量长度不匹配！'
      WRITE(*, *) 'A长度 = ', len_a, '，B长度 = ', len_b
! 终止程序，避免错误计算
      STOP
    ELSE
! 2. 循环计算点积（元素相乘累加）
! 初始化结果
      result = 0.0_8
      DO i=1,len_a
        result = result + a(i)*b(i)
      END DO
    END IF
  END SUBROUTINE DOT_PRODUCT_REALLL

  SUBROUTINE GAUSSIAN_RBF_ARRAY(r_array, epsilon, phi_array, n)
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: n
    REAL(kind=8), INTENT(IN) :: r_array(n)
    REAL(kind=8), INTENT(IN) :: epsilon
    REAL(kind=8), INTENT(OUT) :: phi_array(n)
    REAL(kind=8), PARAMETER :: d_nomal=1.0_8/4.5_8
    INTEGER :: i
    DO i=1,n
      phi_array(i) = (1.0_8-d_nomal*r_array(i))**2
    END DO
  END SUBROUTINE GAUSSIAN_RBF_ARRAY

  SUBROUTINE INVERSE(n, mat, mat_inv)
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: n
    REAL(kind=8), INTENT(IN) :: mat(n, n)
    REAL(kind=8), INTENT(INOUT) :: mat_inv(n, n)
    INTEGER, SAVE :: info=0, i, j
! 临时存储错误信息
    CHARACTER(len=256) :: err_msg
    EXTERNAL DPOTRF
    EXTERNAL DPOTRI
    mat_inv = mat
! Cholesky分解
    CALL DPOTRF('L', n, mat_inv, n, info)
    IF (info .NE. 0) WRITE(err_msg, '(a,i0,a)') &
&                    'inverse: Cholesky decomposition failed (info=', &
&                    info, ')'
! 矩阵求逆
    CALL DPOTRI('L', n, mat_inv, n, info)
    IF (info .NE. 0) WRITE(err_msg, '(a,i0,a)') &
&                    'inverse: Inversion failed (info=', info, ')'
! 填充上三角部分（对称矩阵）
    DO i=1,n
      DO j=i+1,n
        mat_inv(i, j) = mat_inv(j, i)
      END DO
    END DO
  END SUBROUTINE INVERSE

  FUNCTION READOFPOINTSFILEF(filepath) RESULT (points)
    IMPLICIT NONE
    CHARACTER(len=*), INTENT(IN) :: filepath
    REAL(kind=8), ALLOCATABLE :: points(:, :)
!        character(len=256), allocatable :: lines(:)
    INTEGER :: startline, pcount, i, nlines, iostat, file_unit
    CHARACTER(len=256) :: line, bracketsremoved
    REAL(kind=8) :: coords(3)
    INTRINSIC TRIM
    INTRINSIC LEN_TRIM
    file_unit = GET_FREE_UNITT()
    OPEN(unit=file_unit, file=filepath, status='old', action='read', &
&  iostat=iostat) 
    IF (iostat .NE. 0) THEN
      PRINT*, 'Error: Can''t open points file: ', TRIM(filepath)
      ALLOCATE(points(0, 3))
      RETURN
    ELSE
      nlines = 0
      DO 
        READ(file_unit, '(a)', iostat=iostat) 
        IF (iostat .NE. 0) THEN
          REWIND(file_unit) 
!        allocate(lines_defor(nLines))
          DO i=1,nlines
            READ(file_unit, '(a)') lines_defor(i)
          END DO
          CLOSE(file_unit) 
          CALL OFFILE_FINDNITEMSS(lines_defor, startline, pcount)
          IF (pcount .LE. 0) THEN
            PRINT*, 'Error: Invalid point count in ', TRIM(filepath)
            DEALLOCATE(lines_defor)
            ALLOCATE(points(0, 3))
            RETURN
          ELSE
            ALLOCATE(points(pcount, 3))
            DO i=1,pcount
              line = TRIM(lines_defor(startline+i-1))
              bracketsremoved = line(2:LEN_TRIM(line)-1)
              READ(bracketsremoved, *) coords
              points(i, :) = coords
            END DO
!        deallocate(lines_defor)

          END IF
          GOTO 100
        ELSE
          nlines = nlines + 1
        END IF
      END DO
    END IF
 100 CONTINUE
  END FUNCTION READOFPOINTSFILEF

  SUBROUTINE OFFILE_FINDNITEMSS(filelines, startline, itemcount)
    IMPLICIT NONE
    CHARACTER(len=*), INTENT(IN) :: filelines(:)
    INTEGER, INTENT(OUT) :: startline, itemcount
    INTEGER :: i, pos, iostat
    CHARACTER(len=256) :: line
    INTRINSIC SIZE
    INTRINSIC TRIM
    INTRINSIC INDEX
    itemcount = 0
    startline = 0
    DO i=1,SIZE(filelines)
      line = TRIM(filelines(i))
      pos = INDEX(line, 'nPoints') + INDEX(line, 'nFaces') + INDEX(line&
&       , 'size')
      IF (pos .NE. 0) THEN
        READ(line(pos:), *, iostat=iostat) itemcount
        IF (itemcount .GT. 0) THEN
          startline = i + 2
          RETURN
        END IF
      END IF
    END DO
    DO i=1,SIZE(filelines)
      IF (ISNUMBERR(TRIM(filelines(i)))) THEN
        READ(filelines(i), *, iostat=iostat) itemcount
        IF (itemcount .GT. 0) THEN
          startline = i + 2
          RETURN
        END IF
      END IF
    END DO
    DO i=1,SIZE(filelines)
      IF (INDEX(filelines(i), '(') .GT. 0) THEN
        startline = i + 1
        GOTO 100
      END IF
    END DO
 100 itemcount = 0
    DO i=startline,SIZE(filelines)
      IF (INDEX(filelines(i), ')') .GT. 0) THEN
        GOTO 110
      ELSE
        itemcount = itemcount + 1
      END IF
    END DO
 110 CONTINUE
  END SUBROUTINE OFFILE_FINDNITEMSS

! 辅助函数：获取空闲单元号
  INTEGER FUNCTION GET_FREE_UNITT()
    IMPLICIT NONE
    INTEGER :: i, iostat
    LOGICAL :: opened
    DO i=10,999
      INQUIRE(unit=i, opened=opened, iostat=iostat) 
      IF (.NOT.opened .AND. iostat .EQ. 0) THEN
        get_free_unitt = i
        RETURN
      END IF
    END DO
  END FUNCTION GET_FREE_UNITT

  FUNCTION CSV_READ(filename) RESULT (data)
    IMPLICIT NONE
    CHARACTER(len=*), INTENT(IN) :: filename
    REAL*8, ALLOCATABLE :: data(:, :)
    INTEGER :: unit, i, j, nrows, ncols
!		open(newunit=unit, file=filename, status='old')
! 用自定义函数获取有效单元号
    unit = GET_FREE_UNITT()
    OPEN(unit=unit, file=filename, status='old') 
    READ(unit, *) nrows, ncols
    ALLOCATE(data(nrows, ncols))
    DO i=1,nrows
      READ(unit, *) (data(i, j), j=1,ncols)
    END DO
    CLOSE(unit) 
  END FUNCTION CSV_READ

! CSV写入函数（实际使用空格分隔文件）
  SUBROUTINE CSV_WRITE(filename, data, nrows, ncols)
    IMPLICIT NONE
    CHARACTER(len=*), INTENT(IN) :: filename
    INTEGER, INTENT(IN) :: nrows, ncols
    REAL*8, INTENT(IN) :: data(nrows, ncols)
    INTEGER :: unit, i, j
! 打开文件
!		open(newunit=unit, file=filename, status='replace')
    unit = GET_FREE_UNITT()
    OPEN(unit=unit, file=filename, status='replace') 
! 写入行数和列数
    WRITE(unit, '(i5, i5)') nrows, ncols
! 写入数据
    DO i=1,nrows
      WRITE(unit, '(99f10.6)') (data(i, j), j=1,ncols)
    END DO
    CLOSE(unit) 
  END SUBROUTINE CSV_WRITE

! 辅助函数：判断是否为数字
  LOGICAL FUNCTION ISNUMBERR(str)
    IMPLICIT NONE
    CHARACTER(len=*), INTENT(IN) :: str
    REAL(kind=8) :: num
    INTEGER :: iostat
    isnumberr = .false.
    READ(str, *, iostat=iostat) num
    IF (iostat .EQ. 0) isnumberr = .true.
  END FUNCTION ISNUMBERR

END MODULE MESHDEFORMATIONN_DIFF

