!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 29 Jul 2025 17:17
!
MODULE TYPESMODULE_DIFF
  IMPLICIT NONE
  INTRINSIC VERIFY, FINDLOC, SYSTEM, MATMUL, DOT_PRODUCT, MOVE_ALLOC, &
&     NEW_LINE, HUGE, INT
! 仅保留外部声明    
  EXTERNAL DPOTRF, DPOTRI
! 统一定义64位整数和实数常量
! 8字节整数:real64可精确存储 15-17 位十进制有效数字,指数范围是 10⁻³⁰⁸~10³⁰⁸.因此完全可存�
!��4.06575815E-20
  INTEGER, PARAMETER :: int64=8
! 8字节实数（双精度）
  INTEGER, PARAMETER :: real64=8
  CHARACTER(len=256), ALLOCATABLE :: lines_defor(:)
!!!!!!!!!!!!!!!!Buflow
!    real(kind=8), allocatable :: first5_refs(:,:)  ! 形状(5,3)!!!!!!!!!!!!
  REAL(kind=8), ALLOCATABLE :: temp_cellpts(:, :)
  INTEGER(kind=8), ALLOCATABLE :: currentboundary(:)
  REAL(kind=8), ALLOCATABLE :: p_eps(:), gradp(:, :), p_matrix(:, :), &
& temp_grad(:, :, :), facevals(:, :)
  REAL(kind=8), ALLOCATABLE :: gradpb(:, :), p_matrixb(:, :), temp_gradb&
& (:, :, :), facevalsb(:, :)
  REAL(kind=8), ALLOCATABLE :: sj(:), sjcount(:), rj(:), rjsjf(:, :)
  REAL(kind=8), ALLOCATABLE :: sjb(:), rjb(:), rjsjfb(:, :)
  REAL(kind=8), ALLOCATABLE :: eps2(:), eps4(:)
  REAL(kind=8), ALLOCATABLE :: eps2b(:), eps4b(:)
  REAL(kind=8), ALLOCATABLE :: timefluxes(:), surfaceareas(:)
  REAL(kind=8), ALLOCATABLE :: timefluxess(:), surfaceareass(:)
  REAL(kind=8), ALLOCATABLE :: facerhot(:, :), cellrhot(:, :)
  REAL(kind=8), ALLOCATABLE :: facevel(:), positionn(:)
  REAL(kind=8), ALLOCATABLE :: eps22(:), eps44(:), diffusionflux(:), &
& unitfa(:), fd(:), farownerfd(:), farneighbourfd(:), epss(:, :)
  REAL(kind=8), ALLOCATABLE :: eps22b(:), diffusionfluxb(:), unitfab(:)&
& , fdb(:), epssb(:, :)
  REAL(kind=8), ALLOCATABLE :: fdeltas(:, :), fdgrads(:, :, :)
  REAL(kind=8), ALLOCATABLE :: fdeltasb(:, :), fdgradsb(:, :, :)
  REAL(kind=8), ALLOCATABLE :: fluxresiduals(:, :), dt_val(:)
  REAL(kind=8), ALLOCATABLE :: fluxresidualsb(:, :)
  CHARACTER(len=256), ALLOCATABLE :: blines(:)
  CHARACTER(len=256), ALLOCATABLE :: lines_neighbour(:)
  CHARACTER(len=256), ALLOCATABLE :: lines_owner(:)
  INTEGER(kind=8), ALLOCATABLE :: pts_faces(:)
  CHARACTER(len=1000), ALLOCATABLE :: lines_faces(:)
! 面的节点索引
!	real(kind=8), allocatable :: first5_refs(:,:)
  TYPE FACETYPE
      INTEGER(kind=8), ALLOCATABLE :: points(:)
  END TYPE FACETYPE
  TYPE FACEARRAY
      TYPE(FACETYPE), ALLOCATABLE :: faces(:)
  END TYPE FACEARRAY
  TYPE(FACETYPE), ALLOCATABLE :: tmp_faces(:)
  REAL(kind=8), ALLOCATABLE :: encodeprimitives3dd(:, :)
  INTEGER(kind=8), ALLOCATABLE :: boundarynumfacess(:), &
& boundarystartfacess(:)
  REAL(kind=8), ALLOCATABLE :: initialvalues(:)
  REAL(kind=8), ALLOCATABLE :: cellstate_sln(:, :)
  REAL(kind=8), ALLOCATABLE :: cellstate_slnb(:, :)
  REAL(kind=8), ALLOCATABLE :: cellfluxes_sln(:, :)
  REAL(kind=8), ALLOCATABLE :: cellfluxes_slnb(:, :)
  REAL(kind=8), ALLOCATABLE :: cellprimitives_sln(:, :)
  REAL(kind=8), ALLOCATABLE :: cellprimitives_slnb(:, :)
  REAL(kind=8), ALLOCATABLE :: fluxresiduals_sln(:, :)
  REAL(kind=8), ALLOCATABLE :: fluxresiduals_slnb(:, :)
  REAL(kind=8), ALLOCATABLE :: facefluxes_sln(:, :)
  REAL(kind=8), ALLOCATABLE :: facefluxes_slnb(:, :)
  INTEGER(kind=8), ALLOCATABLE :: cells_mesh(:, :)
  REAL(kind=8), ALLOCATABLE :: cvols_mesh(:)
  REAL(kind=8), ALLOCATABLE :: cvols_meshb(:)
  REAL(kind=8), ALLOCATABLE :: ccenters_mesh(:, :)
  REAL(kind=8), ALLOCATABLE :: ccenters_meshb(:, :)
  REAL(kind=8), ALLOCATABLE :: cellsizes_mesh(:, :)
  INTEGER(kind=8), ALLOCATABLE :: faces_mesh(:, :)
  REAL(kind=8), ALLOCATABLE :: favecs_mesh(:, :)
  REAL(kind=8), ALLOCATABLE :: favecs_meshb(:, :)
  REAL(kind=8), ALLOCATABLE :: fcenters_mesh(:, :)
  REAL(kind=8), ALLOCATABLE :: fcenters_meshb(:, :)
  INTEGER(kind=8), ALLOCATABLE :: boundaryfaces_mesh(:, :)
  REAL(kind=8), ALLOCATABLE :: dt_solve(:)
  REAL(kind=8), ALLOCATABLE :: sol(:, :)
  REAL(kind=8), ALLOCATABLE :: facepts(:, :)
  REAL(kind=8), ALLOCATABLE :: faceptsb(:, :)
  REAL(kind=8), ALLOCATABLE :: fcs(:, :), cell_favecs(:, :)
  REAL(kind=8), ALLOCATABLE :: fcsb(:, :), cell_favecsb(:, :)
  REAL(kind=8), ALLOCATABLE :: cellpts(:, :)
  INTEGER(kind=8), ALLOCATABLE :: cellfacecount(:)
  REAL(kind=8), ALLOCATABLE :: uunitvec(:)
  REAL(kind=8), ALLOCATABLE :: uunitvecb(:)
  REAL(kind=8), ALLOCATABLE :: points_tempmesh(:, :)
  REAL(kind=8), ALLOCATABLE :: points_tempmeshb(:, :)
!!!!!!!!!meshdeformation
  REAL(kind=8), ALLOCATABLE :: points_meshdefor(:, :), mat_inv(:, :)
  REAL(kind=8), ALLOCATABLE :: wing_coords(:, :), wing_update_coords(:, &
& :), inoutput_coords(:, :), r_row(:), phi_row(:)
  REAL(kind=8), ALLOCATABLE :: control_points(:, :)
  REAL(kind=8), ALLOCATABLE :: phi(:, :), distances(:)
  INTEGER(kind=8), ALLOCATABLE :: owner_tempmesh(:), neighbour_tempmesh(&
& :)
  INTEGER(kind=8), ALLOCATABLE :: facepoints_tempmesh(:, :)
  REAL(kind=8), ALLOCATABLE :: point_update(:, :)
  REAL(kind=8), ALLOCATABLE :: point_updateb(:, :)
  REAL(kind=8), ALLOCATABLE :: wing(:, :), inoutput(:, :)
  real(kind=8) :: drag_value
  REAL(kind=8), ALLOCATABLE :: cellprimitivesout_adj(:, :), cellprimitivesoutb_adj(:, :)
  REAL(kind=8) :: data_4d137_adj(1, 4), data_4d137b_adj(1, 4)
  
END MODULE TYPESMODULE_DIFF

