!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 29 Jul 2025 17:17
!
MODULE MAIN_MODULE_DIFF
  USE BUFLOWMODULE_DIFF
  USE MESHDEFORMATIONN_DIFF
!!!!!!!!!!      
!!!!!!!!!!	 
  IMPLICIT NONE

CONTAINS
! 模块内包含子程序，自动生成显式接口
  SUBROUTINE MAIN(data_4d137, cellprimitivesout)
    USE TYPESMODULE_DIFF
    IMPLICIT NONE
! 输入参数：仅原data_4D137的第一个维度（标量）
!        real(kind=8), allocatable, intent(out) :: fluxResidualsOut(:,:) 
    REAL(kind=8), ALLOCATABLE :: fluxresidualsoutb(:, :)
    REAL(kind=8), ALLOCATABLE, INTENT(OUT) :: cellprimitivesout(:, :)
    REAL(kind=8), ALLOCATABLE :: cellprimitivesoutb(:, :)
!		real(kind=8), intent(out) :: cellPrimitivesout_1	      
! 局部变量：构造1×4变形参数
    REAL(kind=8), INTENT(IN) :: data_4d137(1, 4)
    REAL(kind=8) :: data_4d137b(1, 4)
! 传递变形网格点的变量
    INTEGER(kind=8) :: ncells, meshinfo(4), iostat, nlines_points, &
&   file_unit_points, nfaces, nfaceperbdry, nboundaries, nlines_boundary&
&   , file_unit_boundary, nlines_owner, file_unit_owner, &
&   nlines_neighbour, file_unit_neighbour, nlines_faces, file_unit_faces&
&   , startline_faces, fcount, i, bracketl, bracketr, pt_count
    INTEGER(kind=8) :: bcount, startline_boundary, npoints
!        real(kind=8), allocatable :: point_update(:,:)  
    CHARACTER(len=256) :: meshpath, pointsfilepath, boundaryfilepath, &
&   ownerfilepath, neighbourfilepath, facesfilepath, line
    TYPE(MESHDATA) :: tempmesh
    INTRINSIC TRIM
    INTRINSIC INDEX
    INTRINSIC SIZE
    INTRINSIC MAXVAL
    INTRINSIC ALLOCATED
!!!!!!!!!!!!
    data_4d137b(1, 1:4) = 0.0d0
!!!!!!!!!!!!
!!!!!!!!!!!!!!meshdeformation
    file_unit_points = GET_FREE_UNITT()
    meshpath = 'mesh/OFairfoilMesh'
    pointsfilepath = TRIM(meshpath)//'/points'
    OPEN(unit=file_unit_points, file=pointsfilepath, status='old', &
&  action='read', iostat=iostat) 
    nlines_points = 0
    DO 
      READ(file_unit_points, '(a)', iostat=iostat) 
      IF (iostat .NE. 0) THEN
        REWIND(file_unit_points) 
        ALLOCATE(lines_defor(nlines_points))
        boundaryfilepath = TRIM(meshpath)//'/boundary'
        file_unit_boundary = GET_FREE_UNIT()
        OPEN(unit=file_unit_boundary, file=boundaryfilepath, status=&
&      'old', action='read', iostat=iostat) 
        nlines_boundary = 0
        DO 
          READ(file_unit_boundary, '(a)', iostat=iostat) 
          IF (iostat .NE. 0) THEN
            REWIND(file_unit_boundary) 
            ALLOCATE(blines(nlines_boundary))
            DO i=1,nlines_boundary
              READ(file_unit_boundary, '(a)') blines(i)
            END DO
            CLOSE(file_unit_boundary) 
            CALL OFFILE_FINDNITEMSSS(blines, startline_boundary, bcount)
            ALLOCATE(boundarynumfacess(bcount))
            ALLOCATE(boundarystartfacess(bcount))
            ownerfilepath = TRIM(meshpath)//'/owner'
            file_unit_owner = GET_FREE_UNIT()
            OPEN(unit=file_unit_owner, file=ownerfilepath, status='old'&
&          , action='read', iostat=iostat) 
            IF (iostat .NE. 0) THEN
              PRINT*, 'Error: Can''t open owner file: ', TRIM(meshpath)
              RETURN
            ELSE
              nlines_owner = 0
              DO 
                READ(file_unit_owner, '(a)', iostat=iostat) 
                IF (iostat .NE. 0) THEN
                  REWIND(file_unit_owner) 
                  ALLOCATE(lines_owner(nlines_owner))
! 2. 打开文件（与owner逻辑完全一致）
                  neighbourfilepath = TRIM(meshpath)//'/neighbour'
                  file_unit_neighbour = GET_FREE_UNIT()
                  OPEN(unit=file_unit_neighbour, file=neighbourfilepath&
&                , status='old', action='read', iostat=iostat) 
                  IF (iostat .NE. 0) THEN
! 错误信息与owner格式统
                    PRINT*, 'Error: Can''t open neighbour file: ', TRIM(&
&                   meshpath)
                    RETURN
                  ELSE
                    nlines_neighbour = 0
                    DO 
! 逐行读取计数
                      READ(file_unit_neighbour, '(a)', iostat=iostat) 
                      IF (iostat .NE. 0) THEN
                        REWIND(file_unit_neighbour) 
! 重置文件指针
                        ALLOCATE(lines_neighbour(nlines_neighbour))
! 分配存储所有行的数组
                        facesfilepath = TRIM(meshpath)//'/faces'
                        file_unit_faces = GET_FREE_UNIT()
                        OPEN(unit=file_unit_faces, file=facesfilepath, &
&                      status='old', action='read', iostat=iostat) 
                        IF (iostat .NE. 0) THEN
                          PRINT*, 'Error: Can''t open faces file: ', &
&                         TRIM(meshpath)
!            allocate(faces%faces(0))
                          RETURN
                        ELSE
                          nlines_faces = 0
                          DO 
                            READ(file_unit_faces, '(a)', iostat=iostat) 
                            IF (iostat .NE. 0) THEN
                              REWIND(file_unit_faces) 
                              ALLOCATE(lines_faces(74151))
                              DO i=1,nlines_faces
                                READ(file_unit_faces, '(a)') lines_faces&
&                              (i)
                              END DO
                              CLOSE(file_unit_faces) 
                              CALL OFFILE_FINDNITEMSSS(lines_faces, &
&                                                startline_faces, fcount&
&                                               )
                              ALLOCATE(tmp_faces(fcount))
!       do i = 1, fCount
!      		allocate(tmp_faces(i)%points(4))
!       end do
                              PRINT*, 'ABC'
                              DO i=1,2
                                line = TRIM(lines_faces(startline_faces+&
&                                 i-1))
                                bracketl = INDEX(line, '(')
                                bracketr = INDEX(line, ')')
                                READ(line(1:bracketl-1), *) pt_count
                              END DO
                              ALLOCATE(pts_faces(pt_count), source=&
&                             0_int64)
!		allocate(wing_update(99, 2), source=0.0_real64)
!!!!!!!!!!!!!!
!!!!!!!!!!!!!!Buflow
                              ALLOCATE(owner_tempmesh(0))
                              ALLOCATE(neighbour_tempmesh(0))
                              ALLOCATE(facepoints_tempmesh(0, 0))
                              PRINT*, 'A'
                              ALLOCATE(points_tempmesh(37243, 3))
                              CALL READOPENFOAMMESHH(meshpath, tempmesh)
                              PRINT*, 'ABC'
                              npoints = SIZE(points_tempmesh, 1)
                              nfaces = SIZE(owner_tempmesh)
                              ncells = MAXVAL(owner_tempmesh)
!四种边界
                              nboundaries = SIZE(tempmesh%boundarynames)
!所有边界面的总数
                              nfaceperbdry = SIZE(tempmesh%&
&                               boundarynumfaces)
                              ALLOCATE(currentboundary(nfaceperbdry))
                              ALLOCATE(gradp(ncells, 3))
                              ALLOCATE(sj(ncells))
                              ALLOCATE(sjcount(ncells))
                              ALLOCATE(rj(ncells))
                              ALLOCATE(rjsjf(nfaces, 2), source=0.0_8)
                              ALLOCATE(eps2(nfaces), source=0.0_8)
                              ALLOCATE(eps4(nfaces), source=0.0_8)
                              ALLOCATE(p_matrix(ncells, 1))
                              ALLOCATE(facevals(nfaces, 5))
!		allocate(P_eps(nCells))
                              ALLOCATE(temp_grad(ncells, 1, 3))
!这个是正确写法，错误写法在程序运行完之后会报错。正确写法和错误写法结果一样
                              ALLOCATE(timefluxes(ncells))
                              ALLOCATE(surfaceareas(ncells))
                              ALLOCATE(timefluxess(ncells))
                              ALLOCATE(surfaceareass(ncells))
                              ALLOCATE(facerhot(nfaces, 2), source=0.0_8&
&                             )
                              ALLOCATE(cellrhot(ncells, 2), source=0.0_8&
&                             )
                              ALLOCATE(facevel(3))
                              ALLOCATE(positionn(3))
                              ALLOCATE(fdeltas(nfaces, 5), source=0.0_8)
                              ALLOCATE(fdgrads(ncells, 5, 3))
                              ALLOCATE(eps22(nfaces))
                              ALLOCATE(eps44(nfaces))
                              ALLOCATE(epss(nfaces, 2), source=0.0_8)
                              ALLOCATE(diffusionflux(5))
                              ALLOCATE(unitfa(3))
                              ALLOCATE(fd(5))
                              ALLOCATE(farownerfd(5))
                              ALLOCATE(farneighbourfd(5))
                              ALLOCATE(facevals_dd(nfaces, 5))
                              ALLOCATE(facevals_d(nfaces, 5))
                              ALLOCATE(fluxresiduals(ncells, 5), source=&
&                             0.0_8)
!        allocate(fluxResidualss(nCells, 5), source=0.0_8) 
                              ALLOCATE(dt_val(ncells), source=0.0_8)
!		allocate(first5_refs(5,3))	
                              ALLOCATE(encodeprimitives3dd(ncells, 5))
                              ALLOCATE(initialvalues(5))
! 分配结构体数组
                              ALLOCATE(cellprimitives_sln(ncells, 5), &
&                             source=0.0d0)
                              ALLOCATE(cellstate_sln(ncells, 5), source=&
&                             0.0d0)
                              ALLOCATE(cellfluxes_sln(ncells, 15), &
&                             source=0.0d0)
                              ALLOCATE(fluxresiduals_sln(ncells, 5), &
&                             source=0.0d0)
                              ALLOCATE(facefluxes_sln(nfaces, 15), &
&                             source=0.0d0)
                              ALLOCATE(faces_mesh(nfaces, 2))
                              ALLOCATE(favecs_mesh(nfaces, 3))
                              ALLOCATE(fcenters_mesh(nfaces, 3))
                              ALLOCATE(cells_mesh(ncells, 6))
                              ALLOCATE(cvols_mesh(ncells))
                              ALLOCATE(ccenters_mesh(ncells, 3))
                              ALLOCATE(cellsizes_mesh(ncells, 3))
                              ALLOCATE(boundaryfaces_mesh(nboundaries, &
&                             MAXVAL(tempmesh%boundarynumfaces)))
                              ALLOCATE(dt_solve(ncells))
                              ALLOCATE(sol(ncells, 5))
                              ALLOCATE(fcs(6, 3))
                              ALLOCATE(cell_favecs(6, 3))
                              ALLOCATE(cellpts(0, 3))
!        allocate(cellPtss(1,3)) 
                              ALLOCATE(facepts(SIZE(facepoints_tempmesh(&
&                             1, :)), 3))
                              ALLOCATE(cellfacecount(ncells))
                              ALLOCATE(uunitvec(3))
!        allocate(points_tempMesh(size(point_update,1), size(point_update,2))) !在readOFPointsFilef里面已经allocate
                              ALLOCATE(points_meshdefor(37254, 3), &
&                             source=0.0_8)
                              ALLOCATE(inoutput(99, 2))
                              ALLOCATE(wing(99, 2))
                              ALLOCATE(wing_coords(99, 2))
                              ALLOCATE(inoutput_coords(99, 2))
                              ALLOCATE(control_points(198, 2))
                              ALLOCATE(r_row(198))
                              ALLOCATE(phi_row(198))
                              ALLOCATE(mat_inv(198, 198), source=0.0_8)
                              ALLOCATE(distances(198))
                              ALLOCATE(phi(198, 198))
                              ALLOCATE(point_update(npoints, 3))
!!!!!!!!!!!!!!Buflow
!       !$AD intent(out) :: cellPrimitives(nCells, 5)  ! 强制 Tapenade 识别维度（nCells 已定义）[-0.75d0, 0.485d0, -0.
!588d0, -0.912d0]
! 构造变形参数（仅第一个维度为输入，其余为0）        
! 读取网格
!		meshPath = "mesh/OFairfoilMesh"	
!		mesh = OpenFOAMMesh(meshPath, point_update)
! 修改后的代码
!		meshInfo = unstructuredMeshInfo(mesh) 
!		nCells = meshInfo(1)  
!		allocate(cellPrimitives(nCells, 5)) 
                              ALLOCATE(cellprimitivesout(18513, 5), &
&                             source=0.0_8)
                              ALLOCATE(cellprimitivesoutb(18513, 5), &
&                             source=0.0_8)
                              PRINT*, 'ABC'
! 调用网格变形，获取变形后的网格点（point_update）
                              CALL AIRFOIL_DEFORMATION_HH(data_4d137)
                              PRINT*, 'ABC'
! 调用CFD计算，传入变形网格点，输出结果到cellPrimitives
                              CALL COMPUTE_CFD(cellprimitivesout)
                              ALLOCATE(fluxresidualsout(18513, 5), &
&                             source=0.0_8)
                              ALLOCATE(fluxresidualsoutb(18513, 5), &
&                             source=1.0_8)
							  CALL COMPUTE_STEADY_RESIDUAL_B(data_4d137, data_4d137b, &
&   cellPrimitivesout, cellPrimitivesoutb, fluxResidualsOut, fluxResidualsOutb)
!                              CALL COMPUTE_STEADY_RESIDUAL(data_4d137, &
!&                                                    cellprimitivesout, &
!&                                                    fluxresidualsout)
! 释放point_update内存        
!!!!!!!!!!!!meshdeformation  
                              DEALLOCATE(lines_defor)
                              IF (ALLOCATED(inoutput)) THEN
                                DEALLOCATE(inoutput)
                              END IF
                              IF (ALLOCATED(wing)) THEN
                                DEALLOCATE(wing)
                              END IF
                              IF (ALLOCATED(point_update)) THEN
                                DEALLOCATE(point_update)
                              END IF
                              IF (ALLOCATED(points_meshdefor)) THEN
                                DEALLOCATE(points_meshdefor)
                              END IF
                              IF (ALLOCATED(mat_inv)) THEN
                                DEALLOCATE(mat_inv)
                              END IF
                              IF (ALLOCATED(wing_coords)) THEN
                                DEALLOCATE(wing_coords)
                              END IF
                              IF (ALLOCATED(inoutput_coords)) THEN
                                DEALLOCATE(inoutput_coords)
                              END IF
                              IF (ALLOCATED(r_row)) THEN
                                DEALLOCATE(r_row)
                              END IF
                              IF (ALLOCATED(phi_row)) THEN
                                DEALLOCATE(phi_row)
                              END IF
                              IF (ALLOCATED(control_points)) THEN
                                DEALLOCATE(control_points)
                              END IF
                              IF (ALLOCATED(phi)) THEN
                                DEALLOCATE(phi)
                              END IF
                              IF (ALLOCATED(distances)) THEN
                                DEALLOCATE(distances)
                              END IF
                              IF (ALLOCATED(fluxresidualsout)) THEN
                                DEALLOCATE(fluxresidualsout)
                              END IF
!		if (allocated(wing_update)) deallocate(wing_update)
!!!!!!!!!!!! meshdeformation
!!!!!!!!!!!! Buflow
                              DEALLOCATE(currentboundary)
!        deallocate(P_eps)
                              DEALLOCATE(p_matrix)
                              DEALLOCATE(temp_grad)
                              DEALLOCATE(gradp)
                              DEALLOCATE(sj)
                              DEALLOCATE(sjcount)
                              DEALLOCATE(rj)
                              DEALLOCATE(rjsjf)
                              DEALLOCATE(eps2)
                              DEALLOCATE(eps4)
                              DEALLOCATE(facevals)
                              DEALLOCATE(timefluxes)
                              DEALLOCATE(surfaceareas)
                              DEALLOCATE(timefluxess)
                              DEALLOCATE(surfaceareass)
                              DEALLOCATE(facevel)
                              DEALLOCATE(positionn)
                              DEALLOCATE(facerhot)
                              DEALLOCATE(cellrhot)
                              DEALLOCATE(epss)
                              DEALLOCATE(fdeltas)
                              DEALLOCATE(fdgrads)
                              DEALLOCATE(eps22)
                              DEALLOCATE(eps44)
                              DEALLOCATE(diffusionflux)
                              DEALLOCATE(unitfa)
                              DEALLOCATE(fd)
                              DEALLOCATE(farownerfd)
                              DEALLOCATE(farneighbourfd)
                              DEALLOCATE(facevals_dd)
                              DEALLOCATE(facevals_d)
                              DEALLOCATE(fluxresiduals)
                              DEALLOCATE(dt_val)
                              PRINT*, 'Aa'
                              DEALLOCATE(blines)
                              PRINT*, 'c'
!		if (allocated(lines_neighbour)) deallocate(lines_neighbour)
!     	deallocate()
                              PRINT*, 'c'
                              DEALLOCATE(lines_owner)
                              PRINT*, 'Aa'
                              DEALLOCATE(lines_faces)
                              DEALLOCATE(pts_faces)
                              DEALLOCATE(tmp_faces)
                              DEALLOCATE(dt_solve)
!		deallocate(first5_refs(5,3))
                              DEALLOCATE(fcs)
                              DEALLOCATE(cell_favecs)
                              DEALLOCATE(cellpts)
                              DEALLOCATE(cellfacecount)
                              DEALLOCATE(facepts)
                              DEALLOCATE(uunitvec)
                              PRINT*, 'Aa'
!!!!!!!!!!!! Buflow		
                              GOTO 100
                            ELSE
                              nlines_faces = nlines_faces + 1
                            END IF
                          END DO
                        END IF
                      ELSE
                        nlines_neighbour = nlines_neighbour + 1
                      END IF
                    END DO
                  END IF
                ELSE
                  nlines_owner = nlines_owner + 1
                END IF
              END DO
            END IF
          ELSE
            nlines_boundary = nlines_boundary + 1
          END IF
        END DO
      ELSE
        nlines_points = nlines_points + 1
      END IF
    END DO
 100 CONTINUE
  END SUBROUTINE MAIN

  SUBROUTINE READOPENFOAMMESHH(polymeshpath, tempmesh)
    IMPLICIT NONE
    CHARACTER(len=*), INTENT(IN) :: polymeshpath
    TYPE(MESHDATA), INTENT(OUT) :: tempmesh
    CHARACTER(len=256) :: pointsfilepath, facesfilepath, ownerfilepath, &
&   neighbourfilepath, boundaryfilepath
    INTRINSIC TRIM
    pointsfilepath = TRIM(polymeshpath)//'/points'
    facesfilepath = TRIM(polymeshpath)//'/faces'
    ownerfilepath = TRIM(polymeshpath)//'/owner'
    neighbourfilepath = TRIM(polymeshpath)//'/neighbour'
    boundaryfilepath = TRIM(polymeshpath)//'/boundary'
    CALL READOFPOINTSFILE(pointsfilepath)
    facepoints_tempmesh = READOFFACESFILE(facesfilepath)
    owner_tempmesh = READOFOWNERFILE(ownerfilepath)
    neighbour_tempmesh = READOFNEIGHBOURFILE(neighbourfilepath)
    CALL READOFBOUNDARYFILE(boundaryfilepath, tempmesh%boundarynames, &
&                     tempmesh%boundarynumfaces, tempmesh%&
&                     boundarystartfaces)
  END SUBROUTINE READOPENFOAMMESHH

  SUBROUTINE OFFILE_FINDNITEMSSS(filelines, startline, itemcount)
    IMPLICIT NONE
    CHARACTER(len=*), INTENT(IN) :: filelines(:)
    INTEGER(kind=8), INTENT(OUT) :: startline, itemcount
    INTEGER(kind=8) :: i, pos, iostat
    CHARACTER(len=256) :: line
    INTRINSIC SIZE
    INTRINSIC TRIM
    INTRINSIC INDEX
    itemcount = 0
    startline = 0
    DO i=1,SIZE(filelines)
      line = TRIM(filelines(i))
      pos = INDEX(line, 'nPoints') + INDEX(line, 'nFaces') + INDEX(line&
&       , 'size')
      IF (pos .NE. 0) THEN
        READ(line(pos:), *, iostat=iostat) itemcount
        IF (itemcount .GT. 0) THEN
          startline = i + 2
          RETURN
        END IF
      END IF
    END DO
    DO i=1,SIZE(filelines)
      IF (ISNUMBERRR(TRIM(filelines(i)))) THEN
        READ(filelines(i), *, iostat=iostat) itemcount
        IF (itemcount .GT. 0) THEN
          startline = i + 2
          RETURN
        END IF
      END IF
    END DO
    DO i=1,SIZE(filelines)
      IF (INDEX(filelines(i), '(') .GT. 0) THEN
        startline = i + 1
        GOTO 100
      END IF
    END DO
 100 itemcount = 0
    DO i=startline,SIZE(filelines)
      IF (INDEX(filelines(i), ')') .GT. 0) THEN
        GOTO 110
      ELSE
        itemcount = itemcount + 1
      END IF
    END DO
 110 CONTINUE
  END SUBROUTINE OFFILE_FINDNITEMSSS

  LOGICAL FUNCTION ISNUMBERRR(str)
    IMPLICIT NONE
    CHARACTER(len=*), INTENT(IN) :: str
    REAL(kind=8) :: num
    INTEGER(kind=8) :: iostat
    isnumberrr = .false.
    READ(str, *, iostat=iostat) num
    IF (iostat .EQ. 0) isnumberrr = .true.
  END FUNCTION ISNUMBERRR

END MODULE MAIN_MODULE_DIFF

